const books=[
['Antygona','Sofokles','antyk • tragedia','Po wojnie o Teby Kreon zakazuje pochówku Polinejkesa, uznanego za zdrajcę. Antygona, przekonana, że nakaz bogów i obowiązek wobec brata stoją wyżej niż rozkaz władcy, grzebie ciało. Ismena odmawia pomocy ze strachu. Kreon skazuje Antygonę na zamurowanie mimo próśb Hajmona i ostrzeżeń Tejrezjasza. Gdy cofa decyzję, jest za późno: Antygona, Hajmon i Eurydyka popełniają samobójstwo.','Antygona jest dumna, odważna i bezkompromisowa; chce godnego pochówku brata, lecz jej konflikt polega na niemożności pogodzenia dwóch równorzędnych racji. Nie zmienia przekonań, ale świadomie przyjmuje śmierć. Kreon chce umocnić państwo i autorytet prawa. Z rozsądnego władcy staje się tyranem; dopiero katastrofa uczy go pokory.','Konflikt tragiczny, prawo boskie i ludzkie, przeznaczenie, władza, bunt, rodzina, samotność, pycha. Symbole: niepogrzebane ciało oznacza naruszenie ładu; grób Antygony jest granicą życia i śmierci.','Upór obu stron prowadzi do katastrofy. Antygona broni wartości, lecz zamyka się na kompromis; Kreon popełnia hybris i traci rodzinę. Tragedia pyta, czy legalne prawo zawsze jest moralne.','Konteksty: „Dziady III” – bunt jednostki wobec przemocy; „Rok 1984” – prawo jako narzędzie władzy; Biblia – nadrzędność prawa moralnego.'],
['Makbet','William Szekspir','renesans • tragedia szekspirowska','Po zwycięskiej bitwie wiedźmy przepowiadają Makbetowi koronę. Pod wpływem ambicji i Lady Makbet morduje króla Dunkana, a następnie Banka i rodzinę Makdufa, by ukryć zbrodnię. Tyran coraz bardziej ufa dwuznacznym przepowiedniom. Lady Makbet popada w obłęd i umiera. Las Birnam „rusza”, Makduf – człowiek „niezrodzony z kobiety” – zabija Makbeta, a tron obejmuje Malkolm.','Makbet zaczyna jako lojalny, odważny rycerz. Chce wielkości, lecz boi się moralnych skutków. Pierwsza zbrodnia niszczy granice; z człowieka rozdartego staje się samotnym tyranem. Lady Makbet początkowo jest silniejsza i manipuluje mężem, potem winy nie potrafi wyprzeć i psychicznie się rozpada.','Ambicja, władza, zbrodnia, wina, kara, sumienie, przeznaczenie i wolna wola, pozór. Krew symbolizuje niezmywalną winę; noc – moralny chaos; las Birnam – spełnienie proroctwa.','Przepowiednia nie zmusza Makbeta do zbrodni: bohater wybiera środki. Każde przestępstwo rodzi następne, a władza oparta na strachu niszczy sprawcę i państwo.','Konteksty: „Zbrodnia i kara” – psychologia winy; „Balladyna” – zbrodnia dla władzy; „Antygona” – pycha władcy.'],
['Dziady cz. III','Adam Mickiewicz','romantyzm • dramat romantyczny','Gustaw przemienia się w Konrada, więźnia i poetę. W Wielkiej Improwizacji żąda od Boga „rządu dusz”, lecz przegrywa przez pychę. Ksiądz Piotr pokornie modli się i otrzymuje widzenie Polski jako narodu-męczennika. Sceny więzienne pokazują represje młodzieży; Salon warszawski – podział społeczeństwa; historia Rollisona – okrucieństwo Senatora. Finał zapowiada dalszą walkę.','Konrad pragnie wolności narodu i mocy zdolnej go ocalić. Jego problemem są samotność, prometejska pycha i stawianie własnego geniuszu ponad Bogiem. Nie osiąga dojrzałej przemiany, lecz zostaje ocalony dzięki modlitwie. Ksiądz Piotr jest jego pokornym przeciwieństwem.','Patriotyzm, martyrologia, mesjanizm, bunt, wolność, samotność, cierpienie, walka dobra ze złem, sen i widzenie. Cela oznacza niewolę; lawa – ukrytą siłę narodu; liczba 44 – tajemniczego wybawcę.','Dramat zestawia bunt indywidualisty z pokorą kapłana. Cierpienie narodu może budować wspólnotę, ale mesjanizm grozi usprawiedliwianiem ofiar. Społeczeństwo jest podzielone na patriotów i oportunistów.','Konteksty: Prometeusz; Biblia – Hiob, Chrystus i Apokalipsa; „Wesele” – diagnoza narodu; historia filomatów i represji carskich.'],
['Pan Tadeusz','Adam Mickiewicz','romantyzm • epopeja narodowa','Tadeusz wraca do Soplicowa i wikła się w uczucia do Telimeny i Zosi. Spór Sopliców z Horeszkami o zamek prowadzi do zajazdu, przerwanego przez Moskali. Ksiądz Robak organizuje powstanie i ratuje Hrabiego; przed śmiercią ujawnia, że jest Jackiem Soplicą. Otrzymuje przebaczenie Gerwazego. Po wkroczeniu wojsk Napoleona Tadeusz i Zosia zaręczają się, a chłopi uzyskują wolność.','Jacek Soplica jako porywczy szlachcic zabija Stolnika, zostaje uznany za zdrajcę i przeżywa moralny upadek. Jako Robak służy ojczyźnie, rezygnuje z dumy i przez ofiarę odzyskuje dobre imię. Tadeusz dojrzewa od impulsywnego młodzieńca do odpowiedzialnego gospodarza.','Ojczyzna, emigracja, pamięć, dom, tradycja, miłość, przemiana, natura, spór i zgoda. Soplicowo symbolizuje utraconą ojczyznę; koncert Jankiela – pamięć historii; polonez – wspólnotę i kres epoki.','Utwór idealizuje świat szlachecki, ale pokazuje jego kłótliwość i anachronizmy. Pamięć ocala tożsamość emigrantów. Prywatne winy można odkupić służbą wspólnocie.','Konteksty: „Przedwiośnie” – różne obrazy ojczyzny; „Wesele” – wspólnota pozorna; biografia emigracyjna Mickiewicza.'],
['Lalka','Bolesław Prus','pozytywizm • powieść realistyczna','Wokulski, były powstaniec i przedsiębiorca, pomnaża majątek na wojnie rosyjsko-tureckiej, by zdobyć Izabelę Łęcką. Ratuje finanse jej rodziny, wchodzi do arystokracji i idealizuje kobietę. Pomaga ubogim i wspiera naukę. Gdy w pociągu odkrywa flirt Izabeli ze Starskim, próbuje się zabić. Jego dalszy los pozostaje niejasny; Rzecki umiera, a świat starych ideałów znika.','Wokulski łączy romantyczne uczucie z pozytywistycznym kultem pracy. Chce miłości i społecznego awansu, lecz przegrywa z własną idealizacją oraz barierami klasowymi. Od aktywnego przedsiębiorcy przechodzi ku rozpaczy i zniknięciu. Rzecki żyje pamięcią Wiosny Ludów i nadzieją polityczną; Izabela traktuje ludzi przez pryzmat pozycji.','Miłość, praca, pieniądz, nierówności, samotność, marzenie kontra rzeczywistość, miasto, pamięć, nauka. Lalka oznacza uprzedmiotowienie i iluzję; Warszawa jest społecznym laboratorium; pamiętnik Rzeckiego – odchodzący świat.','Powieść pyta, czy jednostka może przekroczyć klasowe granice. Miłość może motywować, ale oparta na projekcji staje się niszcząca. Praca daje sens, lecz nie usuwa samotności.','Konteksty: „Przedwiośnie” – diagnoza społeczeństwa; „Zbrodnia i kara” – miasto i wykluczenie; „Cierpienia młodego Wertera” – idealizacja miłości.'],
['Zbrodnia i kara','Fiodor Dostojewski','realizm • powieść psychologiczna','Ubogo żyjący Raskolnikow tworzy teorię ludzi nadzwyczajnych i zabija lichwiarkę Alonę oraz przypadkową świadka Lizawietę. Nie potrafi wykorzystać łupu. Choroba, lęk i rozmowy z Porfirym ujawniają rozpad psychiczny. Sonia, zmuszona przez biedę do prostytucji, okazuje mu współczucie i prowadzi ku przyznaniu się. Na Syberii bohater zaczyna duchowe odrodzenie.','Raskolnikow chce sprawdzić własną wyjątkowość i rzekomo pomóc ludziom. Jego kłopotem jest konflikt teorii z sumieniem. Od pychy, izolacji i racjonalizacji przechodzi przez cierpienie do uznania winy; pełna przemiana dopiero się zaczyna. Sonia zachowuje godność dzięki wierze i miłości.','Wina, kara, sumienie, pycha, ubóstwo, poświęcenie, wiara, odkupienie, samotność. Sen o zarzynanej szkapie ujawnia współczucie; krzyż – przyjęcie winy; Petersburg – duszną przestrzeń moralnego kryzysu.','Kara psychiczna zaczyna się przed wyrokiem. Żadna idea nie usprawiedliwia odebrania życia, bo człowieka nie da się sprowadzić do równania użyteczności. Relacja z drugim człowiekiem umożliwia odrodzenie.','Konteksty: „Makbet” – lawina zbrodni; Biblia – Łazarz i nawrócenie; Nietzsche (krytycznie) – nadczłowiek; „Dżuma” – odpowiedzialność za innych.'],
['Wesele','Stanisław Wyspiański','Młoda Polska • dramat symboliczny','W bronowickiej chacie odbywa się wesele inteligenta z chłopką. Rozmowy ujawniają fascynację wsią, stereotypy i brak porozumienia. Nocą gości odwiedzają zjawy będące materializacją win i pragnień. Wernyhora wręcza Gospodarzowi złoty róg, znak wezwania do powstania. Jasiek gubi go, schylając się po czapkę z piór. Chochoł pogrąża wszystkich w bezwładnym tańcu.','Bohaterem zbiorowym jest społeczeństwo. Inteligencja pragnie wielkiej idei, lecz brakuje jej sprawczości; chłopi mają energię, ale nie ufają elitom. Gospodarz uchyla się od odpowiedzialności, Jasiek wybiera próżność. Zamiast przemiany następuje potwierdzenie narodowej niemocy.','Naród, niepodległość, konflikt klas, chłopomania, pamięć historyczna, marazm, sztuka, taniec. Złoty róg – szansa; czapka z piór – próżność; chochoł – uśpienie i możliwość odrodzenia; taniec – bezwład.','Diagnoza jest gorzka: wspólnota nie powstaje z deklaracji, gdy brak zaufania, organizacji i odpowiedzialności. Widma każą bohaterom skonfrontować się z historią.','Konteksty: „Dziady III” – naród i niewola; „Tango” – taniec jako znak klęski; rabacja galicyjska; „Przedwiośnie” – spór o kształt Polski.'],
['Przedwiośnie','Stefan Żeromski','dwudziestolecie • powieść polityczna','Cezary Baryka dorasta w Baku, zachwyca się rewolucją, a potem widzi jej terror i śmierć matki. Z ojcem wyrusza do Polski, słuchając mitu szklanych domów; Seweryn umiera w drodze. Cezary walczy w wojnie polsko-bolszewickiej, poznaje ziemiańską Nawłoć i biedny Chłodek. Spiera się z Gajowcem i komunistą Lulkiem. W finale idzie na czele demonstracji, osobno od tłumu.','Cezary chce znaleźć ojczyznę i program sprawiedliwej Polski. Jego problemem jest brak jednoznacznego autorytetu i rozczarowanie każdą ideologią. Od naiwnego rewolucjonisty przechodzi do krytycznego, samotnego poszukiwacza; finał pozostawia jego wybór otwarty.','Dojrzewanie, rewolucja, wojna, ojczyzna, utopia, nierówność, autorytet, tożsamość. Szklane domy – piękny mit modernizacji; przedwiośnie – niedojrzałość państwa i nadzieja; marsz – bunt.','Niepodległość nie rozwiązuje automatycznie problemów społecznych. Żeromski pokazuje trzy projekty: utopię Seweryna, reformizm Gajowca i rewolucję Lulka, nie uznając żadnego za kompletny.','Konteksty: „Pan Tadeusz” – idealny obraz Polski; „Lalka” – nierówności; „Rok 1984” – ideologia i język; historia rewolucji rosyjskiej.'],
['Inny świat','Gustaw Herling-Grudziński','literatura łagrowa • wspomnienia','Narrator zostaje aresztowany przez NKWD i trafia do łagru w Jercewie. Opisuje głód, niewolniczą pracę, choroby, donosicielstwo oraz ludzi doprowadzonych do granic moralnych. Spotyka m.in. Kostylewa, który okalecza się, by nie pracować dla systemu. Podejmuje głodówkę i po układzie Sikorski–Majski odzyskuje wolność. Epilog stawia pytanie o ocenę czynów dokonanych w nieludzkich warunkach.','Narrator chce przetrwać bez utraty prawdy o człowieku. Jego problemem jest system, który wymusza egoizm i rozbija solidarność. Uczy się, że nie wolno łatwo sądzić ofiar, ale też nie należy uznawać zła za normę. Kostylew broni resztki wolności przez autodestrukcję.','Zniewolenie, godność, głód, praca, samotność, solidarność, granice moralności, pamięć i świadectwo. Łagier to „inny świat” z odwróconymi normami; ręka Kostylewa – bolesna własność samego siebie.','Totalitaryzm niszczy nie tylko ciało, lecz więzi i język wartości. Ekstremalne warunki wyjaśniają zachowania, ale nie powinny usuwać rozróżnienia dobra i zła. Świadectwo przywraca ofiarom imiona.','Konteksty: „Rok 1984” – totalitaryzm; Borowski – człowiek zlagrowany; „Zdążyć przed Panem Bogiem” – godność w sytuacji granicznej.'],
['Zdążyć przed Panem Bogiem','Hanna Krall','reportaż literacki','Hanna Krall rozmawia z Markiem Edelmanem, zastępcą dowódcy powstania w getcie warszawskim. Reportaż splata obrazy Zagłady, selekcji i powstania z powojenną pracą Edelmana jako kardiologa. Bohater mówi rzeczowo, odrzuca patos i pokazuje walkę jako wybór sposobu umierania. Jako lekarz próbuje „wyprzedzić” Boga, przedłużając życie pacjentów.','Edelman jest świadkiem, uczestnikiem i lekarzem. Chce ocalić konkretnego człowieka oraz prawdę bez upiększeń. Jego kłopotem jest pamięć o tych, których nie udało się uratować. Nie tyle się zmienia, ile przenosi wojenną odpowiedzialność za życie do medycyny.','Zagłada, pamięć, godność, śmierć, heroizm bez patosu, przypadek, odpowiedzialność, ocalenie. Mur getta – izolacja; numerki życia – iluzoryczna kontrola; serce – kruche życie i obowiązek lekarza.','W sytuacji bez wyjścia godność może polegać na zachowaniu prawa do decyzji. Tekst podważa pomnikowy język heroizmu, przywracając indywidualność ofiarom.','Konteksty: „Inny świat”; Borowski; „Antygona” – godny pochówek; etyka świadectwa i historia powstania w getcie.'],
['Dżuma','Albert Camus','XX wiek • powieść-parabola','W Oranie wybucha epidemia. Doktor Rieux od początku nazywa zagrożenie i leczy chorych. Tarrou organizuje oddziały sanitarne, Rambert początkowo chce uciec do ukochanej, lecz zostaje z mieszkańcami. Paneloux interpretuje epidemię religijnie, a po śmierci dziecka komplikuje swój sąd. Dżuma ustępuje, ale Tarrou umiera; Rieux ujawnia się jako narrator i ostrzega, że bakcyl nigdy nie ginie.','Rieux jest lekarzem i etycznym realistą: chce uczciwie wykonywać pracę, nie udając bohatera. Rambert zmienia się z człowieka skupionego na prywatnym szczęściu w członka wspólnoty. Tarrou szuka „świętości bez Boga”, lecz nie zostaje ocalony.','Zło, cierpienie, śmierć, solidarność, poświęcenie, absurd, bunt, samotność i wspólnota. Dżuma to epidemia, ale też parabola wojny i każdego zła; zamknięte miasto – doświadczenie wygnania.','Nie da się ostatecznie pokonać zła, można jednak odmówić współudziału. Sens rodzi się z solidarnego działania mimo braku gwarancji zwycięstwa. Cierpienie niewinnego dziecka podważa proste teodycee.','Konteksty: egzystencjalizm Camusa; okupacja Francji; „Inny świat”; „Antygona” – działanie w imię wartości.'],
['Rok 1984','George Orwell','antyutopia • powieść polityczna','Winston Smith fałszuje przeszłość w Ministerstwie Prawdy, ale potajemnie buntuje się przeciw Partii. Z Julią tworzy zakazany związek i wierzy, że O’Brien należy do oporu. Zostają zdradzeni, uwięzieni i torturowani. W pokoju 101 Winston zdradza Julię. Po reedukacji nie tylko jest posłuszny – kocha Wielkiego Brata.','Winston chce prawdy, pamięci, miłości i prywatności. Jego kłopotem jest system kontrolujący ciało, język i świadomość. Z biernego sceptyka staje się buntownikiem, po czym zostaje psychicznie złamany. Julia buntuje się praktycznie, lecz nie buduje spójnej alternatywy.','Totalitaryzm, propaganda, język, pamięć, prawda, wolność, miłość, strach. Wielki Brat – wszechobecna kontrola; teleekran – brak prywatności; pokój 101 – najgłębszy lęk; nowomowa – ograniczenie myślenia.','Państwo totalitarne nie zadowala się posłuszeństwem: chce przejąć definicję rzeczywistości. Gdy zanika język i pamięć, opór staje się niemal niemożliwy. Prywatna miłość jest polityczna, bo tworzy lojalność poza Partią.','Konteksty: stalinizm; „Inny świat”; „Przedwiośnie” – mechanizm rewolucji; „Dziady III” – przemoc państwa.'],
['Tango','Sławomir Mrożek','współczesność • dramat groteskowy','W domu Stomila i Eleonory nie obowiązują żadne normy. Artur buntuje się przeciw chaosowi rodziców i próbuje przywrócić formę przez ślub z Alą. Odkrywa jej zdradę z Edkiem, a jego program okazuje się pusty. Edek zabija Artura i przejmuje władzę. Finałowe tango Edka z Eugeniuszem oznacza triumf brutalnej siły.','Artur jest młodym intelektualistą, który chce ładu, tradycji i sensu. Jego problemem jest brak żywej idei: forma staje się celem samym w sobie. Od racjonalnego reformatora przechodzi ku pokusie przemocy, ale przegrywa. Edek, pozornie prosty, wykorzystuje próżnię wartości.','Bunt, konflikt pokoleń, forma, wolność, anarchia, władza, przemoc, groteska. Tango – masowa kultura i zwycięstwo prostactwa; rupieciarnia – chaos; ślub – bezskuteczna próba odbudowy formy.','Całkowite odrzucenie norm nie daje wolności, lecz tworzy przestrzeń dla silniejszego. Intelekt bez przekonującej wartości przegrywa z przemocą. Bunt może stać się konserwatywny, gdy poprzednie pokolenie zniosło zakazy.','Konteksty: „Wesele” – taniec klęski; „Rok 1984” – mechanizm władzy; Gombrowicz – forma; rewolucja obyczajowa.'],
['Mitologia','Jan Parandowski','antyk • opowieści mityczne','Zbiór porządkuje greckie opowieści o bogach i herosach. Prometeusz wykrada ogień i cierpi za ludzi; Syzyf oszukuje bogów i zostaje skazany na bezsensowną pracę; Orfeusz schodzi po Eurydykę, lecz traci ją przez zwątpienie; Dedal i Ikar próbują ucieczki; Demeter odzyskuje Korę tylko na część roku. Mity tłumaczą świat i modelowe ludzkie doświadczenia.','Prometeusz chce dobra ludzkości i płaci za bunt; Orfeusz chce pokonać śmierć miłością, lecz nie wytrzymuje próby; Ikar pragnie przekroczyć granice i ignoruje ostrzeżenia; Syzyf chce przechytrzyć los. Bohaterowie są archetypami, nie realistycznymi psychologiami.','Poświęcenie, bunt, wina i kara, miłość, śmierć, pycha, przeznaczenie, podróż. Ogień – wiedza i cywilizacja; labirynt – zagubienie; nić Ariadny – ratunek; puszka Pandory – źródło nieszczęść i nadzieja.','Mity pokazują granice człowieka i cenę ich przekraczania. Jednocześnie ustanawiają wzorce obecne w późniejszej kulturze; kontekst mitologiczny pozwala nazwać postawy jednym archetypem.','Konteksty: Konrad jako Prometeusz; Syzyf u Camusa; Ikar w malarstwie Bruegla; Orfeusz wobec motywu miłości silniejszej niż śmierć.'],
['Treny','Jan Kochanowski','renesans • cykl trenologiczny','Cykl dziewiętnastu utworów powstał po śmierci Urszulki. Poeta przedstawia dziecko, własny ból i kryzys dotychczasowej filozofii. W Trenach IX–XI podważa wartość mądrości, cnoty i pobożności. Szuka córki w różnych wizjach zaświatów. W Trenie XIX śni o matce z Urszulką; odzyskuje częściową równowagę, przyjmując ludzką zmienność.','Podmiot to ojciec, poeta i renesansowy humanista. Chce zrozumieć śmierć oraz ocalić pamięć córki. Jego problemem jest zderzenie stoickich zasad z doświadczeniem. Z pewnego mędrca staje się człowiekiem wątpiącym, potem dojrzale godzi rozum, uczucie i wiarę.','Żałoba, miłość rodzicielska, śmierć, kryzys światopoglądu, pamięć, wiara, poezja. Pustka w domu – nieobecność; oliwka – kruche dziecko; sen – pocieszenie i kontakt z porządkiem metafizycznym.','Cierpienie obnaża kruchość deklarowanych zasad. Cykl nie wraca naiwnie do dawnego ładu: proponuje zgodę na zmienność losu i prawo człowieka do rozpaczy. Prywatna strata zostaje podniesiona do rangi uniwersalnego doświadczenia.','Konteksty: Księga Hioba; „Lament świętokrzyski”; stoicyzm i epikureizm; „Zdążyć przed Panem Bogiem” – pamięć o zmarłych.'],
['Potop','Henryk Sienkiewicz','pozytywizm • powieść historyczna','Andrzej Kmicic przybywa na Laudę, zaręcza się z Oleńką, ale przez porywczość i kompanów traci jej zaufanie. Przysięga Radziwiłłowi, nie wiedząc o zdradzie magnata. Gdy poznaje prawdę, działa jako Babinicz: broni Jasnej Góry, ratuje króla i walczy ze Szwedami. List królewski ujawnia jego zasługi, a Oleńka mu wybacza.','Kmicic chce miłości Oleńki i rycerskiej sławy. Jego kłopotem są impulsywność, źle rozumiana lojalność i utrata dobrego imienia. Przechodzi pełną przemianę: od awanturnika do odpowiedzialnego patrioty, a czyny – nie deklaracje – stają się pokutą.','Przemiana, patriotyzm, zdrada i wierność, odwaga, miłość, honor, wspólnota. Jasna Góra – duchowy opór; przybrane nazwisko – odcięcie od win i praca nad nową tożsamością.','Odkupienie jest możliwe przez długotrwałą służbę. Powieść „ku pokrzepieniu serc” buduje wspólnotowy mit zwycięstwa, upraszcza jednak historię i idealizuje część postaw.','Konteksty: Jacek Soplica; „Makbet” – odmienny kierunek przemiany; historia potopu szwedzkiego; etos rycerski.'],
['Chłopi','Władysław Reymont','Młoda Polska • epopeja chłopska','Cztery tomy odpowiadają porom roku. Boryna poślubia młodą Jagnę, choć kocha ją jego syn Antek. Konflikt o ziemię rozbija rodzinę. Podczas walki o las Boryna zostaje ciężko ranny, a Antek trafia do więzienia. Jagna łamie normy wspólnoty i zostaje brutalnie wywieziona ze wsi. Boryna umiera, symbolicznie siejąc ziemię; życie Lipiec trwa dalej.','Maciej Boryna jest gospodarzem podporządkowanym ziemi i pozycji; przed śmiercią jednoczy się z rytmem natury. Antek chce samodzielności, ziemi i Jagny; dojrzewa do roli gospodarza. Jagna pragnie uczuć i swobody, ale jest bierna wobec nacisku; wspólnota czyni z niej kozła ofiarnego.','Ziemia, praca, natura, tradycja, wspólnota, miłość, konflikt pokoleń, wykluczenie. Pory roku – cykl życia; ziemia – wartość, tożsamość i władza; wesele – rytuał społeczny.','Gromada chroni porządek, lecz potrafi być okrutna. Jednostka jest zależna od natury, ekonomii i obyczaju. Moralność wspólnoty stosuje podwójne standardy wobec kobiet i mężczyzn.','Konteksty: „Wesele” – obraz chłopów; „Antygona” – jednostka kontra zbiorowość; naturalizm; biblijny siewca.'],
['Balladyna','Juliusz Słowacki','romantyzm • dramat fantastyczny','Kirkor szuka dobrej żony. Balladyna i Alina rywalizują w zbieraniu malin; Balladyna zabija siostrę i wychodzi za Kirkora. Kolejne zbrodnie ukrywają pierwszą: wypiera się matki, zabija Grabca i Kostryna, przejmuje władzę. Jako królowa wydaje sprawiedliwe wyroki za własne czyny, po czym ginie rażona piorunem.','Balladyna chce awansu, miłości i władzy. Jej problemem jest przekonanie, że zbrodnię można odłączyć od konsekwencji. Z ambitnej dziewczyny staje się bezwzględną władczynią; resztki sumienia ujawniają się w sądzie, lecz za późno. Alina i Wdowa stanowią moralny kontrast.','Zbrodnia i kara, ambicja, władza, siostrzana rywalizacja, wina, natura, fantastyka. Plama na czole – niezmywalna wina; maliny – niewinność przemieniona w krew; piorun – wyższa sprawiedliwość.','Każda zbrodnia tworzy potrzebę następnej i prowadzi do samotności. Sprawiedliwość ostatecznie obejmuje także władcę. Groteskowe połączenie baśni, historii i tragedii ujawnia mechanizm żądzy władzy.','Konteksty: „Makbet”; „Zbrodnia i kara”; mit Kaina i Abla; „Antygona” – władza i prawo.'],
['Skąpiec','Molier','klasycyzm • komedia charakterów','Harpagon podporządkowuje rodzinę pieniądzom. Chce poślubić Mariannę, ukochaną syna Kleanta, a córkę Elizę wydać bez posagu za Anzelma, choć kocha ona Walerego. Kradzież szkatułki wywołuje panikę. Rozpoznanie rodzinne ujawnia, że Anzelm jest ojcem Marianny i Walerego. Harpagon zgadza się na małżeństwa dzieci, gdy odzyskuje pieniądze i nie musi płacić.','Harpagon jest bogaty, lecz żyje w lęku przed stratą. Chce kontrolować majątek i ludzi; jego problemem jest skąpstwo niszczące relacje. Nie zmienia się naprawdę – finał przywraca porządek młodym, ale on pozostaje przy szkatułce. Kleant i Eliza walczą o prawo do miłości.','Pieniądz, skąpstwo, rodzina, konflikt pokoleń, miłość, małżeństwo, hipokryzja. Szkatułka staje się namiastką osoby i symbolem niewoli posiadania; dom – pole ekonomicznej tyranii.','Dobra materialne nie dają szczęścia, gdy stają się celem. Rodzic traci autorytet, gdy traktuje dzieci jak element transakcji. Komizm śmiechem koryguje wadę, choć Harpagon pozostaje nieuleczony.','Konteksty: „Lalka” – pieniądz i pozycja; „Tango” – konflikt pokoleń; komedia dell’arte i klasyczna zasada decorum.']
];
const motifs=[
['Miłość','„Lalka”, „Treny”, „Zbrodnia i kara”, „Mitologia”, „Pan Tadeusz”','Może ocalać i mobilizować (Sonia), ale idealizowana niszczy (Wokulski); rodzicielska zderza się ze śmiercią (Kochanowski).'],['Bunt','„Antygona”, „Dziady III”, „Tango”, „Rok 1984”, „Mitologia”','Bunt broni wartości, lecz wymaga celu i odpowiedzialności. Konrad grzeszy pychą, Artur nie ma żywej idei, Winston przegrywa z systemem.'],['Władza','„Makbet”, „Balladyna”, „Antygona”, „Rok 1984”, „Tango”','Władza bez kontroli przekształca ambicję w tyranię. Kreon i Makbet tracą bliskich, Partia niszczy samą zdolność myślenia.'],['Wina i kara','„Zbrodnia i kara”, „Makbet”, „Balladyna”, „Mitologia”','Kara zaczyna się w sumieniu, a próba ukrycia winy uruchamia kolejne zbrodnie. Sprawiedliwość bywa psychiczna, prawna lub metafizyczna.'],['Przemiana','Kmicic, Jacek Soplica, Raskolnikow, Cezary Baryka, Rambert','Przemiana wymaga konfrontacji z winą lub cierpieniem. Najpełniejsze są te potwierdzone długim działaniem, nie samą deklaracją.'],['Wolność','„Dziady III”, „Rok 1984”, „Inny świat”, „Antygona”','Wolność to nie tylko brak więzienia, ale prawo do prawdy, pamięci, decyzji i własnego systemu wartości.'],['Cierpienie i śmierć','„Treny”, „Dżuma”, „Inny świat”, „Zdążyć przed Panem Bogiem”, „Antygona”','Cierpienie sprawdza światopogląd. Może izolować, lecz także budować solidarność i zmuszać do odpowiedzialnego działania.'],['Ojczyzna i naród','„Dziady III”, „Pan Tadeusz”, „Wesele”, „Przedwiośnie”, „Potop”','Literatura tworzy mit wspólnoty, diagnozuje jej słabości i pyta, czy patriotyzm jest uczuciem, czynem czy krytyką państwa.'],['Jednostka a społeczeństwo','„Antygona”, „Chłopi”, „Lalka”, „Tango”, „Wesele”','Wspólnota daje tożsamość i normy, ale może wykluczać. Jednostka płaci cenę za sprzeciw lub próbę przekroczenia klasy.'],['Samotność','Konrad, Wokulski, Raskolnikow, Winston, Cezary','Samotność bywa skutkiem pychy, niezrozumienia albo przemocy systemu. Wyjście prowadzi przez relację, wspólnotę i przyjęcie odpowiedzialności.'],['Marzenia i rzeczywistość','„Lalka”, „Przedwiośnie”, „Wesele”, „Pan Tadeusz”','Ideały uruchamiają działanie, ale niesprawdzone stają się iluzją: Izabela, szklane domy i powstańczy sen przegrywają z rzeczywistością.'],['Praca','„Lalka”, „Chłopi”, „Inny świat”, „Dżuma”','Praca może dawać godność i służyć wspólnocie, lecz w systemie przemocy staje się narzędziem zniewolenia.'],['Pamięć','„Pan Tadeusz”, „Lalka”, „Zdążyć przed Panem Bogiem”, „Rok 1984”','Pamięć buduje tożsamość i ocala ofiary; dlatego totalitaryzm próbuje kontrolować przeszłość.'],['Granice człowieczeństwa','„Inny świat”, „Dżuma”, „Zbrodnia i kara”, „Zdążyć przed Panem Bogiem”','Sytuacja graniczna nie daje prostych ocen. Człowieczeństwo ujawnia się w odmowie obojętności i w ochronie konkretnej osoby.']
];
const devices=[['Epitet','określenie rzeczownika','„krwawa korona” – wartościuje i buduje obraz'],['Metafora','przeniesienie znaczenia','„lawą” w „Dziadach III” jest ukryta siła narodu'],['Porównanie','zestawienie przez „jak”, „niczym”','uwydatnia wspólną cechę'],['Personifikacja','nadanie cech ludzkich','natura może osądzać bohatera'],['Symbol','znak o wielu znaczeniach','złoty róg = szansa na czyn narodowy'],['Alegoria','znaczenie ustalone i jednoznaczne','kostucha = śmierć'],['Ironia','sens sprzeczny z dosłownym','demaskuje pozory i dystans narratora'],['Hiperbola','celowe wyolbrzymienie','podkreśla siłę emocji'],['Anafora','powtórzenie na początku wersów/zdań','rytmizuje i wzmacnia argument'],['Antyteza','zestawienie przeciwieństw','rozum – wiara, jednostka – władza'],['Oksymoron','połączenie sprzecznych słów','ujawnia paradoks'],['Pytanie retoryczne','pytanie bez oczekiwanej odpowiedzi','angażuje odbiorcę i eksponuje problem'],['Wyliczenie','szereg elementów','porządkuje lub intensyfikuje opis'],['Onomatopeja','naśladowanie dźwięku','uplastycznia scenę'],['Inwersja','nietypowy szyk','akcentuje wybrane słowo'],['Przerzutnia','przeniesienie składni do następnego wersu','tworzy napięcie i rytm'],['Apostrofa','bezpośredni zwrot','podnosi ton i wskazuje adresata'],['Eufemizm','złagodzenie wyrażenia','może maskować przemoc propagandy'],['Groteska','połączenie sprzecznych jakości','ośmiesza i niepokoi, np. „Tango”'],['Stylizacja','naśladowanie stylu epoki/środowiska','buduje wiarygodność świata']];
const genres=[['Epika','narrator, fabuła, świat przedstawiony','powieść realistyczna, historyczna, psychologiczna, epopeja, opowiadanie, reportaż'],['Liryka','podmiot liryczny, obrazowanie, rytm','hymn, tren, elegia, pieśń, fraszka, sonet'],['Dramat','akcja i dialog, didaskalia, przeznaczenie sceniczne','tragedia antyczna, dramat romantyczny i symboliczny, komedia, dramat groteskowy'],['Powieść-parabola','fabuła ma sens dosłowny i uniwersalny','„Dżuma” – epidemia i model walki ze złem'],['Antyutopia','negatywna wizja społeczeństwa','„Rok 1984” – ostrzeżenie przed totalitaryzmem'],['Reportaż literacki','fakty + środki literackie','„Zdążyć przed Panem Bogiem” – świadectwo i kompozycja rozmowy']];
const eras=[['Antyk','harmonia, mimesis, tragizm, fatum, katharsis, stoicyzm, epikureizm','„Mitologia”, „Antygona”'],['Średniowiecze','teocentryzm, uniwersalizm, pareneza, danse macabre, deesis','Biblia, „Lament świętokrzyski”, „Rozmowa Mistrza Polikarpa…”'],['Renesans','humanizm, antropocentryzm, reformacja, harmonia, carpe diem','Kochanowski, Szekspir'],['Barok','konceptyzm, kontrast, vanitas, niepokój metafizyczny','Morsztyn, Naborowski, Pasek'],['Oświecenie','racjonalizm, empiryzm, klasycyzm, dydaktyzm, satyra','Krasicki, Molier jako ważny kontekst klasycyzmu'],['Romantyzm','irracjonalizm, indywidualizm, ludowość, prometeizm, mesjanizm','Mickiewicz, Słowacki'],['Pozytywizm','realizm, praca organiczna i u podstaw, emancypacja, asymilacja','„Lalka”, „Potop”'],['Młoda Polska','symbolizm, dekadentyzm, impresjonizm, chłopomania, naturalizm','„Wesele”, „Chłopi”'],['Dwudziestolecie','awangarda, katastrofizm, eksperyment, spór o państwo','„Przedwiośnie”'],['Wojna i współczesność','świadectwo, totalitaryzm, egzystencjalizm, absurd, groteska','„Inny świat”, Krall, Camus, Orwell, Mrożek']];
const contexts=[['Biblia','Hiob – cierpienie niezawinione; Kain i Abel – bratobójstwo; Chrystus – ofiara; Apokalipsa – kres i sąd.','Łącz z „Trenami”, „Antygoną”, „Dziadami III”, „Zbrodnią i karą”, wojną.'],['Mitologia','Prometeusz – bunt dla ludzi; Syzyf – absurd; Ikar – przekroczenie granic; Orfeusz – miłość i strata.','Działa przy buncie, poświęceniu, winie, losie, sztuce i miłości.'],['Historia totalitaryzmów','Stalinizm, nazizm, propaganda, łagry i Zagłada.','„Rok 1984”, „Inny świat”, Krall, Borowski, „Dżuma” jako parabola okupacji.'],['Filozofia egzystencjalna','Człowiek żyje bez pewnych odpowiedzi; sens tworzy wyborem i odpowiedzialnością. Camus: absurd i bunt.','„Dżuma”, „Inny świat”, „Rok 1984”, Raskolnikow.'],['Psychologia','Mechanizmy wyparcia, racjonalizacji, traumy; konflikt ideału z realnym „ja”.','Makbet, Raskolnikow, Wokulski, ocaleni z Zagłady.'],['Historia Polski','Zabory i represje, powstania, odzyskanie niepodległości, wojna polsko-bolszewicka.','„Dziady III”, „Pan Tadeusz”, „Wesele”, „Przedwiośnie”, „Potop”.'],['Sztuka','Bruegel „Upadek Ikara”, motyw danse macabre, malarstwo symboliczne.','Jako krótki kontekst do cierpienia, obojętności, śmierci i symbolu.']];
const philosophy=[['Stoicyzm','Cnota i rozum pozwalają przyjąć zmienny los; kontrolujemy postawę, nie wszystkie zdarzenia.','„Treny” pokazują próbę i kryzys stoicyzmu.'],['Epikureizm','Szczęście to brak cierpienia, umiar, przyjaźń i spokój – nie nieograniczona przyjemność.','Kochanowski; kontrast z żądzą Harpagona i Makbeta.'],['Platonizm','Świat idei jest doskonalszy od rzeczywistości zmysłowej.','Idealizacja Izabeli przez Wokulskiego; romantyczny prymat ducha.'],['Racjonalizm','Rozum jest podstawowym źródłem poznania.','Oświecenie; spór z irracjonalizmem w „Romantyczności”.'],['Utylitaryzm','Dobre jest to, co przynosi największy pożytek największej liczbie.','Raskolnikow wypacza rachunek dobra, usprawiedliwiając zabójstwo.'],['Egzystencjalizm','Człowiek jest wolny, odpowiedzialny i sam tworzy sens w świecie bez gwarancji.','Camus, wybory w sytuacjach granicznych, odpowiedzialność Rieux.'],['Personalizm','Każda osoba ma niezbywalną godność i nie może być środkiem do celu.','Krall, Herling-Grudziński; krytyka Raskolnikowa i totalitaryzmu.']];
const questions=`1|Biblia|Motyw cierpienia niezawinionego (Księga Hioba)
2|Biblia|Człowiek wobec niestałości świata (Księga Koheleta)
3|Biblia|Wizja końca świata (Apokalipsa św. Jana)
4|Mitologia|Poświęcenie się w imię wyższych wartości
5|Mitologia|Problematyka winy i kary
6|Mitologia|Miłość silniejsza niż śmierć
7|Iliada|Heroizm w zmaganiu się z losem
8|Antygona|Prawa boskie a prawa ludzkie
9|Antygona|Człowiek wobec przeznaczenia
10|Lament świętokrzyski|Motyw cierpiącej matki
11|Rozmowa Mistrza Polikarpa ze Śmiercią|Motyw tańca śmierci
12|Pieśń o Rolandzie|Średniowieczny wzorzec rycerza
13|Makbet|Moralna odpowiedzialność za czyny
14|Makbet|Czy człowiek decyduje o własnym losie?
15|Makbet|Wpływ sprawowania władzy na człowieka
16|Skąpiec|Czy dobra materialne czynią człowieka szczęśliwym?
17|Skąpiec|Przyczyny nieporozumień między rodzicami a dziećmi
18|Satyry Ignacego Krasickiego|Wady ludzkie w krzywym zwierciadle satyry
19|Romantyczność|Świat ducha a świat rozumu
20|Ballady Mickiewicza|Na czym polega ludowa sprawiedliwość?
21|Dziady cz. III|Losy młodzieży polskiej pod zaborami
22|Dziady cz. III|Mesjanizm jako romantyczna idea poświęcenia
23|Dziady cz. III|Postawy społeczeństwa wobec zaborcy
24|Dziady cz. III|Różne postawy człowieka wobec Boga
25|Dziady cz. III|Prawdy o człowieku ujawniane przez sny albo widzenia
26|Dziady cz. III|Cel nawiązań do motywów biblijnych
27|Dziady cz. III|Walka dobra ze złem o duszę ludzką
28|Dziady cz. III|Czym dla człowieka może być wolność?
29|Dziady cz. III|Motyw samotności
30|Lalka|Miłość – siła destrukcyjna czy motywująca?
31|Lalka|Praca jako pasja człowieka
32|Lalka|Rola majątku i pochodzenia w relacjach
33|Lalka|Konfrontacja marzeń z rzeczywistością
34|Lalka|Miasto – przestrzeń przyjazna czy wroga?
35|Lalka|Czym dla człowieka mogą być wspomnienia?
36|Potop|Postawy odwagi i tchórzostwa
37|Zbrodnia i kara|Walka człowieka ze swoimi słabościami
38|Zbrodnia i kara|Motyw winy i kary
39|Zbrodnia i kara|Ile człowiek jest gotów poświęcić dla innych?
40|Zbrodnia i kara|Co może determinować ludzkie postępowanie?
41|Zbrodnia i kara|Motyw przemiany bohatera
42|Wesele|Co utrudnia porozumienie grup społecznych?
43|Wesele|Rola chłopów i inteligencji w sprawie niepodległości
44|Wesele|Sen o Polsce czy sąd nad Polską?
45|Wesele|Symboliczne znaczenie widm i zjaw
46|Wesele|Motyw tańca
47|Chłopi|Obyczaj i tradycja w życiu społeczeństwa
48|Przedwiośnie|Znaczenie tytułu dla sensu utworu
49|Przedwiośnie|Wojna i rewolucja jako źródła doświadczeń
50|Przedwiośnie|Różne wizje odbudowy Polski
51|Przedwiośnie|Młodość jako czas kształtowania tożsamości
52|Przedwiośnie|Rola autorytetu w życiu człowieka
53|Przedwiośnie|Utopijny i realny obraz rzeczywistości
54|Ferdydurke|Groteskowy obraz świata
55|Ferdydurke|Człowiek wobec presji otoczenia
56|Proszę państwa do gazu|Człowiek zlagrowany jako ofiara systemu
57|Inny świat|Znaczenie tytułu dla sensu utworu
58|Inny świat|Konsekwencje zniewolenia człowieka
59|Zdążyć przed Panem Bogiem|Czy można zachować godność w sytuacji skrajnej?
60|Zdążyć przed Panem Bogiem|Zagłada z perspektywy świadka i uczestnika
61|Zdążyć przed Panem Bogiem|Walka o życie w perspektywie wojennej i powojennej
62|Dżuma|Co skłania człowieka do poświęceń?
63|Dżuma|Człowiek wobec cierpienia i śmierci
64|Dżuma|Czy możliwa jest przyjaźń w sytuacjach skrajnych?
65|Dżuma|Jakie postawy przyjmuje człowiek wobec zła?
66|Rok 1984|Czy możliwe jest zbudowanie doskonałego państwa?
67|Rok 1984|Jak zachować wolność w państwie totalitarnym?
68|Rok 1984|Znaczenie propagandy w państwie totalitarnym
69|Rok 1984|Nowomowa jako sposób ograniczenia wolności
70|Tango|Bunt przeciwko porządkowi społecznemu
71|Tango|Konflikt pokoleń
72|Tango|Normy społeczne – ograniczają czy porządkują życie?
73|Górą Edek|Cel nawiązania do innego utworu literackiego
74|Miejsce|Miejsca ważne w życiu człowieka
75|Profesor Andrews w Warszawie|Stan wojenny z perspektywy obcokrajowca
76|Podróże z Herodotem|Czym dla człowieka może być podróżowanie?`.split('\n').map(x=>x.split('|'));
const evidence={Biblia:'Hiob nie zna przyczyny próby, Kohelet obserwuje przemijanie, a Apokalipsa łączy katastrofę z nadzieją odnowy.',Mitologia:'Prometeusz, Syzyf, Orfeusz i Ikar pokazują modelowe wybory oraz ich konsekwencje.',Iliada:'Achilles zna swój los, lecz wybiera krótkie życie i sławę; Priam odzyskuje ciało Hektora dzięki odwadze i człowieczeństwu.','Lament świętokrzyski':'Maryja mówi jak bezradna matka, nie odległa królowa; emocjonalny monolog humanizuje sacrum.','Rozmowa Mistrza Polikarpa ze Śmiercią':'Śmierć wylicza przedstawicieli wszystkich stanów, przypominając o równości i marności pozycji.','Pieśń o Rolandzie':'Roland jest wierny Bogu, władcy i ojczyźnie, lecz jego duma opóźnia wezwanie pomocy.','Satyry Ignacego Krasickiego':'Karykatura, ironia i wyolbrzymienie ujawniają pijaństwo, modę, hipokryzję i bezmyślność.','Romantyczność':'Karusia doświadcza obecności Jasia, a spór narratora ze Starcem przeciwstawia „czucie i wiarę” szkiełku i oku.','Ballady Mickiewicza':'W „Świteziance” i „Lilijach” zbrodnia zostaje ukarana przez siły natury i porządek moralny.',Ferdydurke:'Józio jest „upupiany”; szkoła, Młodziakowie i dwór narzucają mu kolejne formy.', 'Proszę państwa do gazu':'Tadek przystosowuje się do obozowych reguł; system rozmywa empatię i zmusza ofiary do udziału w machinie.', 'Górą Edek':'Tytułowy Edek nawiązuje do bohatera „Tanga”; intertekstualność pokazuje powrót brutalnej siły w codzienności.',Miejsce:'Zburzona cerkiew istnieje w pamięci narratora i mieszkańców; miejsce przechowuje historię nawet po zniknięciu budynku.','Profesor Andrews w Warszawie':'Obcokrajowiec nie zna języka ani realiów stanu wojennego, dlatego codzienność staje się obca i absurdalna.','Podróże z Herodotem':'Podróż poszerza język, perspektywę i rozumienie innych kultur; Herodot staje się przewodnikiem Kapuścińskiego.'};
const qContext=t=>/wład|państw|totalit|propagand|wolno/.test(t)?'„Rok 1984” lub historyczny kontekst totalitaryzmu':/win|kar|zbrod|sumieni/.test(t)?'„Makbet” albo „Zbrodnia i kara”':/miło|rodzic|matk/.test(t)?'„Treny” lub „Lalka”':/naród|Polsk|niepodleg|zabor/.test(t)?'„Wesele”, „Dziady III” albo historia Polski':/cierp|śmier|skrajn|poświę/.test(t)?'Księga Hioba, „Dżuma” lub „Inny świat”':/bunt|pokole|norm/.test(t)?'„Antygona” albo „Tango”':/pamię|miejsce|podróż/.test(t)?'„Pan Tadeusz” – pamięć i tożsamość':'wybrany mit, Biblia albo druga lektura z podobnym motywem';
const getBook=n=>books.find(b=>n.toLowerCase().includes(b[0].toLowerCase().replace(' cz. III',''))) ;
function qAnswer(q){const b=getBook(q[1]); const ev=evidence[q[1]]||(b?b[3]:'Najpierw wskaż konkretną scenę i decyzję bohatera, potem pokaż jej przyczynę oraz konsekwencję.');return `<p><b>Teza:</b> Literatura pokazuje, że ${q[2].toLowerCase()} zależy od wartości, warunków i odpowiedzialności człowieka; nie jest zjawiskiem jednoznacznym.</p><p><b>Argument z utworu:</b> ${ev}</p><p><b>Kontekst:</b> ${qContext(q[2])}. Nie streszczaj drugiego utworu – nazwij podobieństwo albo różnicę i wyjaśnij, jak wzmacnia tezę.</p><p><b>Wniosek:</b> Ostateczny sens zagadnienia ujawniają skutki wyborów: to one potwierdzają lub podważają deklarowane wartości.</p>`}
const nav=[['start','Plan nauki'],['books','Lektury – 19 opracowań'],['motifs','Motywy literackie'],['oral','76 pytań jawnych CKE'],['mynotes','Moje notatki i komentarze'],['heroes','Bohaterowie i przemiany'],['contexts','Konteksty uniwersalne'],['eras','Epoki i pojęcia'],['philosophy','Filozofia'],['devices','Środki stylistyczne'],['genres','Gatunki literackie'],['essay','Wypracowanie i argumentacja'],['speaking','Schemat odpowiedzi ustnej']];
let state={page:'start',query:'',selectedOnly:false};
let done=JSON.parse(localStorage.getItem('maturaDone')||'{}');
let notes=JSON.parse(localStorage.getItem('maturaNotes')||'{}');
let highlights=JSON.parse(localStorage.getItem('maturaHighlights')||'{}');
let currentUser=null,saveTimer=null,isRegister=false;
let pendingSelection=null;
function check(id,label){return `<label class="check"><input type="checkbox" data-done="${id}" ${done[id]?'checked':''}><span>${label}</span></label>`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function noteBox(id,title){return `<div class="comment-box"><label for="note-${id}">Moja notatka / komentarz <small>zapis automatyczny</small></label><textarea id="note-${id}" data-note="${id}" data-title="${esc(title)}" placeholder="Dopisz skojarzenie, cytat, argument albo własny komentarz…">${esc(notes[id]||'')}</textarea><div class="note-saved" aria-live="polite"></div></div>`}
function annotationsBox(id){const items=highlights[id]||[];return `<section class="annotations" data-annotations="${id}"><h3>Moja notatka z zaznaczeń</h3><p class="annotations-help">Zaznacz tekst powyżej myszką, wybierz podświetlenie lub dodanie notatki. Treść poniżej możesz dowolnie edytować.</p>${items.length?items.map(h=>`<div class="annotation-card"><blockquote class="annotation-quote">„${esc(h.quote)}”</blockquote><textarea data-annotation-note="${id}" data-highlight-id="${h.id}" placeholder="Dopisz własne wyjaśnienie, skojarzenie lub argument…">${esc(h.note||'')}</textarea><div class="annotation-actions"><span class="note-saved">Zapis automatyczny</span><button class="delete-annotation" data-delete-highlight="${id}" data-highlight-id="${h.id}">Usuń</button></div></div>`).join(''):'<div class="annotations-empty">Nie masz jeszcze zaznaczonych fragmentów.</div>'}</section>`}
function renderNav(){navEl.innerHTML=nav.map(([id,n],i)=>`${i===0||i===1||i===3?`<div class="nav-title">${i===0?'START':i===1?'NAUKA':'MATURA USTNA'}</div>`:''}<button data-page="${id}" class="${state.page===id?'active':''}">${n}</button>`).join('')}
function start(){return `<div class="hero"><h2>Twoje centrum powtórek ♡</h2><p>Ucz się warstwami: najpierw fabuła i bohater, potem motywy, na końcu argument oraz kontekst. Zaznaczaj opanowane opracowania – postęp zapisze się na tym urządzeniu.</p></div><div class="stats"><div class="stat"><b>19</b>obszernych lektur</div><div class="stat"><b>76</b>pytań jawnych 2026–2028</div><div class="stat"><b>14</b>motywów z argumentami</div></div><h2 class="section-title">Jak korzystać</h2><div class="grid"><div class="card"><h3>1. Zrozum</h3><p>Przeczytaj ciąg przyczynowo-skutkowy fabuły. Umiej odpowiedzieć: co się stało, dlaczego i z jakim skutkiem.</p></div><div class="card"><h3>2. Połącz</h3><p>Przypisz bohatera do motywu i porównaj z jednym uniwersalnym kontekstem.</p></div><div class="card"><h3>3. Powiedz</h3><p>Wylosuj pytanie, postaw tezę i wypowiedz odpowiedź według schematu: argument – przykład – kontekst – wniosek.</p></div></div>`}
function booksView(){return books.map((b,i)=>`<article class="card book" data-id="b${i}" data-search="${b.join(' ')} ${esc(notes['b'+i]||'')} ${(highlights['b'+i]||[]).map(h=>h.quote+' '+h.note).join(' ')}"><div class="selectable-text"><div class="book-head"><div class="book-no">${i+1}</div><div><h2>${b[0]}</h2><div class="meta">${b[1]} • ${b[2]}</div>${b.slice(5).flatMap(x=>x.match(/[„”A-ZŁŚŻŹĆŃÓ][^,;.]{2,22}/g)||[]).slice(0,4).map(x=>`<span class="tag">${x.replace(/[„”]/g,'')}</span>`).join('')}</div></div><div class="note-grid"><div class="note wide"><h3>Fabuła: co, dlaczego, konsekwencje</h3><p>${b[3]}</p></div><div class="note"><h3>Bohater: cel, problem, zmiana</h3><p>${b[4]}</p></div><div class="note"><h3>Motywy i symbole</h3><p>${b[5]}</p></div><div class="note"><h3>Problematyka</h3><p>${b[6]}</p></div><div class="note"><h3>Konteksty – gdzie użyć</h3><p>${b[7]}</p></div></div></div>${check('b'+i,'Umiem omówić tę lekturę bez zaglądania do notatki')}${annotationsBox('b'+i)}</article>`).join('')}
function tableView(data,heads){return `<div class="card">${data.map(r=>`<div class="motif-row" data-search="${r.join(' ')}"><b>${r[0]}</b><span>${r[1]}</span><span>${r[2]}</span></div>`).join('')}</div>`}
function questionsView(){return `<p class="card">Każde pytanie ma gotowy szkielet odpowiedzi. Rozwiń je i ćwicz wypowiedź przez 5–7 minut.</p>${questions.map(q=>`<details class="question" id="q${q[0]}" data-id="q${q[0]}" data-search="${q.join(' ')} ${(highlights['q'+q[0]]||[]).map(h=>h.quote+' '+h.note).join(' ')}"><summary>${q[0]}. ${q[2]} <span class="meta">— ${q[1]}</span></summary><div class="answer"><div class="selectable-text">${qAnswer(q)}</div>${check('q'+q[0],'Umiem odpowiedzieć samodzielnie')}${annotationsBox('q'+q[0])}</div></details>`).join('')}<p class="source">Lista pytań: komunikat CKE z 30 sierpnia 2024 r. obowiązujący w latach 2026–2028.</p>`}
function labelFor(id){if(id.startsWith('page-')){const page=id.slice(5),entry=nav.find(x=>x[0]===page);return {isQ:false,label:entry?entry[1]:'Dział tematyczny',type:'Dział'}}const isQ=id[0]==='q',item=isQ?questions.find(q=>q[0]===id.slice(1)):books[Number(id.slice(1))];return {isQ,label:isQ?(item?item[0]+'. '+item[2]:'Pytanie'):(item?item[0]:'Lektura'),type:isQ?'Pytanie jawne':'Lektura'}}
function mynotes(){const rows=Object.entries(highlights).flatMap(([id,list])=>{const info=labelFor(id);return list.map(h=>`<article class="card own-note" data-search="${esc(info.label+' '+h.quote+' '+h.note)}"><h3>${esc(info.label)}</h3><div class="meta">${info.type}</div><blockquote class="annotation-quote">„${esc(h.quote)}”</blockquote><textarea data-annotation-note="${id}" data-highlight-id="${h.id}" placeholder="Dopisz własną notatkę…">${esc(h.note||'')}</textarea><button class="note-link" data-goto="${id}">Przejdź do materiału</button></article>`)}).join('');return `<div class="hero"><h2>Moje notatki ♡</h2><p>Tu znajdziesz wszystkie zaznaczone fragmenty i własne dopiski. Każdą notatkę możesz dalej edytować.</p></div><h2 class="section-title">Notatki z zaznaczeń</h2><div class="notes-list">${rows||'<div class="card empty">Nie masz jeszcze notatek. Zaznacz fragment tekstu w dowolnym dziale i wybierz „Dodaj notatkę”.</div>'}</div>`}
function heroes(){return `<div class="grid">${books.map((b,i)=>`<div class="card" data-search="${b[0]} ${b[4]}"><h3>${b[0]}</h3><p>${b[4]}</p></div>`).join('')}</div>`}
function essay(){return `<div class="hero"><h2>Najważniejsza zasada</h2><p>Argument nie jest streszczeniem. To zdanie udowadniające tezę, poparte konkretną sceną i wyjaśnieniem jej znaczenia.</p></div><h2 class="section-title">Schemat akapitu argumentacyjnego</h2><div class="card"><p><b>1. Zdanie argumentu:</b> nazwij zależność, np. „Żądza władzy niszczy moralne granice człowieka”.</p><p><b>2. Przykład:</b> wskaż scenę, decyzję i skutek – Makbet zabija Dunkana, a potem usuwa świadków i staje się tyranem.</p><p><b>3. Interpretacja:</b> wyjaśnij, co przykład dowodzi – pierwsza świadoma zbrodnia ułatwia następne i izoluje bohatera.</p><p><b>4. Miniwniosek:</b> połącz dowód z tezą – władza zdobyta przemocą nie daje bezpieczeństwa.</p></div><h2 class="section-title">Kompozycja wypracowania</h2><div class="grid"><div class="card"><h3>Wstęp</h3><p>Zdefiniuj problem, pokaż jego niejednoznaczność i postaw tezę. Nie zaczynaj od „od zarania dziejów”.</p></div><div class="card"><h3>Rozwinięcie</h3><p>Co najmniej dwa pełne argumenty. Każdy: twierdzenie → konkretny przykład → interpretacja → powrót do tezy. Kontekst ma pracować na argument.</p></div><div class="card"><h3>Zakończenie</h3><p>Zbierz wyniki rozumowania, porównaj przykłady i sformułuj wniosek szerszy niż powtórzenie tezy.</p></div></div><h2 class="section-title">Co trzeba umieć</h2><div class="card"><ul><li>czytać temat i wyłapać czasownik polecenia;</li><li>postawić tezę, którą da się udowodnić;</li><li>przywołać lekturę obowiązkową i konkretną sytuację;</li><li>włączyć kontekst funkcjonalnie, nie jako ozdobę;</li><li>stosować spójniki logiczne: ponieważ, dlatego, jednak, zatem;</li><li>unikać błędów rzeczowych, potoczności i pustych ocen;</li><li>zostawić czas na korektę składni, ortografii i interpunkcji.</li></ul></div>`}
function speaking(){return `<div class="hero"><h2>Odpowiedź ustna w 6 ruchach</h2><p>Nie ucz się całych tekstów na pamięć. Zapamiętaj tok rozumowania i 2–3 sceny z każdej lektury.</p></div><div class="grid">${[['1. Wprowadzenie','Wyjaśnij pojęcie z pytania i zawęź problem.'],['2. Teza','Odpowiedz na pytanie jednym jasnym zdaniem.'],['3. Argument','Nazwij prawidłowość, którą pokaże lektura.'],['4. Przykład','Omów konkretną scenę: przyczyna → decyzja → skutek.'],['5. Kontekst','Porównaj z innym utworem, historią, filozofią lub sztuką.'],['6. Wniosek','Wróć do pytania i pokaż, co wynika z porównania.']].map(x=>`<div class="card"><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div><h2 class="section-title">Gotowy szablon językowy</h2><div class="card"><p>„Zagadnienie … dotyczy … . Uważam, że … . Potwierdza to … w utworze … . Bohater …, ponieważ …, dlatego … . Skutkiem jego decyzji jest … . Podobny / odmienny sposób ujęcia widzimy w … . Ten kontekst pokazuje, że … . Można więc stwierdzić, że … .”</p></div>`}
const views={start,books:booksView,motifs:()=>tableView(motifs),oral:questionsView,mynotes,heroes,contexts:()=>tableView(contexts),eras:()=>tableView(eras),philosophy:()=>tableView(philosophy),devices:()=>tableView(devices),genres:()=>tableView(genres),essay,speaking};
const content=document.querySelector('#content'),navEl=document.querySelector('#nav'),title=document.querySelector('#pageTitle');
function render(keepScroll=false){const y=window.scrollY;title.textContent=nav.find(x=>x[0]===state.page)[1];content.innerHTML=views[state.page]();if(!content.querySelector('[data-id]')&&!['start','mynotes'].includes(state.page)){const pageId='page-'+state.page;content.dataset.id=pageId;content.classList.add('selectable-text');content.insertAdjacentHTML('beforeend',annotationsBox(pageId))}else{content.removeAttribute('data-id');content.classList.remove('selectable-text')}renderNav();applyHighlights();filter();bindInputs();if(keepScroll)window.scrollTo(0,y);else window.scrollTo(0,0)}
function filter(){const q=state.query.toLowerCase().trim();let any=false;content.querySelectorAll('[data-search]').forEach(el=>{const matches=!q||el.dataset.search.toLowerCase().includes(q),selected=!state.selectedOnly||done[el.dataset.id];const show=matches&&selected;el.style.display=show?'':'none';if(show)any=true});content.querySelectorAll('.filter-empty').forEach(x=>x.remove());if((q||state.selectedOnly)&&!any)content.insertAdjacentHTML('beforeend','<div class="empty filter-empty">Brak pasujących materiałów. Zmień frazę lub wyłącz filtr zaznaczonych.</div>')}
function bindInputs(){document.querySelectorAll('[data-done]').forEach(x=>x.onchange=()=>{done[x.dataset.done]=x.checked;persist();progress();filter()});document.querySelectorAll('[data-note]').forEach(x=>x.oninput=()=>{notes[x.dataset.note]=x.value;persist()});document.querySelectorAll('[data-annotation-note]').forEach(x=>x.oninput=()=>{const h=(highlights[x.dataset.annotationNote]||[]).find(v=>v.id===x.dataset.highlightId);if(h)h.note=x.value;persist()})}
function applyHighlights(){document.querySelectorAll('[data-id]').forEach(container=>{for(const h of highlights[container.dataset.id]||[]){const root=container.matches('.selectable-text')?container:(container.querySelector('.selectable-text')||container),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement.closest('mark,textarea,button,.annotations')||!node.data.includes(h.quote))continue;const at=node.data.indexOf(h.quote),before=node.splitText(at);before.splitText(h.quote.length);const mark=document.createElement('mark');mark.className='user-highlight';mark.dataset.highlightId=h.id;before.replaceWith(mark);mark.append(before);break}}})}
function addHighlight(withNote){if(!pendingSelection)return;const {materialId,quote}=pendingSelection,id=Date.now().toString(36)+Math.random().toString(36).slice(2,6);(highlights[materialId]||(highlights[materialId]=[])).push({id,quote,note:''});hideSelectionTools();persist();render(true);if(withNote)setTimeout(()=>{const input=document.querySelector(`[data-annotation-note="${materialId}"][data-highlight-id="${id}"]`);if(input){input.focus();input.scrollIntoView({behavior:'smooth',block:'center'})}},50)}
function hideSelectionTools(){document.querySelector('#selectionTools').classList.remove('show');pendingSelection=null;window.getSelection()?.removeAllRanges()}
function captureSelection(event){setTimeout(()=>{const sel=window.getSelection(),quote=sel?.toString().trim();if(!quote||quote.length<2||quote.length>600){if(!event?.target?.closest?.('#selectionTools'))hideSelectionTools();return}const node=sel.anchorNode?.nodeType===3?sel.anchorNode.parentElement:sel.anchorNode;if(node?.closest?.('.annotations')){hideSelectionTools();return}const selectable=node?.closest?.('.selectable-text'),material=selectable?.closest('[data-id]')||(selectable?.matches?.('[data-id]')?selectable:null);if(!material){hideSelectionTools();return}const rect=sel.getRangeAt(0).getBoundingClientRect(),tools=document.querySelector('#selectionTools');pendingSelection={materialId:material.dataset.id,quote};tools.style.left=Math.max(8,Math.min(window.innerWidth-260,rect.left+rect.width/2-120))+'px';tools.style.top=Math.max(8,rect.top-52)+'px';tools.classList.add('show')},0)}
function progress(){const total=books.length+questions.length,n=Object.values(done).filter(Boolean).length,p=Math.round(n/total*100);document.querySelector('#progressText').textContent=p+'%';document.querySelector('#progressBar').style.width=p+'%'}
function localSave(){localStorage.setItem('maturaDone',JSON.stringify(done));localStorage.setItem('maturaNotes',JSON.stringify(notes));localStorage.setItem('maturaHighlights',JSON.stringify(highlights))}
function persist(){localSave();clearTimeout(saveTimer);saveTimer=setTimeout(syncToCloud,650)}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2400)}
const cfg=window.VADEMECUM_CONFIG||{},cloudReady=cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase;
const db=cloudReady?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
async function syncToCloud(){if(!db||!currentUser)return;document.querySelector('#syncState').textContent='Zapisywanie…';const {error}=await db.from('vademecum_user_data').upsert({user_id:currentUser.id,payload:{done,notes,highlights},updated_at:new Date().toISOString()});document.querySelector('#syncState').textContent=error?'Błąd zapisu':'Zapisano w chmurze';if(error)toast('Nie udało się zsynchronizować. Dane zostały lokalnie.')}
async function loadCloud(){if(!db||!currentUser)return;document.querySelector('#syncState').textContent='Synchronizacja…';const {data,error}=await db.from('vademecum_user_data').select('payload').eq('user_id',currentUser.id).maybeSingle();if(data?.payload){done=data.payload.done||{};notes=data.payload.notes||{};highlights=data.payload.highlights||{};localSave()}else if(!error){await syncToCloud()}document.querySelector('#syncState').textContent=error?'Zapis lokalny':'Zapisano w chmurze';render();progress()}
function accountUI(){const b=document.querySelector('#accountBtn');b.textContent=currentUser?'◉ '+currentUser.email.split('@')[0]:'♡ Zaloguj się';document.querySelector('#syncState').textContent=currentUser?'Zapisano w chmurze':'Zapis lokalny'}
async function initAuth(){if(!db){accountUI();return}const {data}=await db.auth.getSession();currentUser=data.session?.user||null;accountUI();if(currentUser)await loadCloud();db.auth.onAuthStateChange((event,session)=>{currentUser=session?.user||null;accountUI()})}
function openAuth(){if(currentUser){if(confirm('Wylogować się z konta?'))db.auth.signOut().then(()=>{currentUser=null;accountUI();toast('Wylogowano')});return}if(!cloudReady){toast('Najpierw uzupełnij config.js danymi Supabase');return}document.querySelector('#authDialog').showModal()}
async function submitAuth(){const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value,err=document.querySelector('#authError'),btn=document.querySelector('#authSubmit');err.textContent='';if(!email||password.length<6){err.textContent='Podaj poprawny e-mail i hasło mające co najmniej 6 znaków.';return}btn.disabled=true;btn.textContent='Chwileczkę…';const result=isRegister?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});btn.disabled=false;btn.textContent=isRegister?'Utwórz konto':'Zaloguj się';if(result.error){err.textContent=result.error.message;return}if(result.data.session){currentUser=result.data.user;document.querySelector('#authDialog').close();accountUI();await loadCloud();toast('Zalogowano i zsynchronizowano dane')}else{err.textContent='Sprawdź pocztę i kliknij link potwierdzający konto.'}}
document.addEventListener('click',e=>{const action=e.target.closest('[data-selection-action]');if(action){addHighlight(action.dataset.selectionAction==='note');return}const del=e.target.closest('[data-delete-highlight]');if(del){highlights[del.dataset.deleteHighlight]=(highlights[del.dataset.deleteHighlight]||[]).filter(h=>h.id!==del.dataset.highlightId);persist();render(true);toast('Usunięto zaznaczenie');return}const b=e.target.closest('[data-page]');if(b){state.page=b.dataset.page;state.query='';document.querySelector('#search').value='';render();document.querySelector('#sidebar').classList.remove('open')}const go=e.target.closest('[data-goto]');if(go){const id=go.dataset.goto;state.page=id.startsWith('page-')?id.slice(5):(id[0]==='q'?'oral':'books');render();setTimeout(()=>{const el=document.querySelector(`[data-id="${id}"]`);if(el){if(el.tagName==='DETAILS')el.open=true;el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('search-hit');setTimeout(()=>el.classList.remove('search-hit'),1600)}},50)}});
document.addEventListener('mouseup',captureSelection);
document.addEventListener('touchend',captureSelection);
document.addEventListener('mousedown',e=>{if(!e.target.closest('#selectionTools')&&!e.target.closest('.selectable-text'))hideSelectionTools()});
document.querySelector('#search').addEventListener('input',e=>{state.query=e.target.value;filter()});
document.querySelector('#selectedOnly').addEventListener('change',e=>{state.selectedOnly=e.target.checked;filter()});
document.querySelector('#menu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');
document.querySelector('#accountBtn').onclick=openAuth;
document.querySelector('#authSubmit').onclick=submitAuth;
document.querySelector('#authSwitch').onclick=()=>{isRegister=!isRegister;document.querySelector('#authTitle').textContent=isRegister?'Utwórz konto':'Zaloguj się';document.querySelector('#authSubmit').textContent=isRegister?'Utwórz konto':'Zaloguj się';document.querySelector('#authSwitch').textContent=isRegister?'Masz już konto? Zaloguj się':'Nie masz konta? Zarejestruj się';document.querySelector('#authError').textContent=''};
document.querySelector('#randomBtn').onclick=()=>{const q=questions[Math.floor(Math.random()*questions.length)];state.page='oral';state.query='';render();setTimeout(()=>{const el=document.querySelector('#q'+q[0]);el.open=true;el.scrollIntoView({behavior:'smooth',block:'center'})},50)};
render();progress();initAuth();
