(()=>{
const LEVELS=[
 ['A0','Start','Alfabet, liczby, be/have, pierwsze zdania i pytania.'],
 ['A1','Fundament','Codzienność, Present Simple/Continuous, proste reakcje.'],
 ['A2','Samodzielność','Przeszłość, przyszłość, modalne i krótkie teksty.'],
 ['B1','Matura podstawowa','Pewne rozumienie, 14 tematów i pisanie 100–150 słów.'],
 ['B2/C1','Rozszerzenie','Precyzja, transformacje, kolokacje i tekst 200–250 słów.']
];
const STRATEGIES=[
 ['Słuchanie',['Przeczytaj polecenie i odpowiedzi przed nagraniem.','Podkreśl różnice między odpowiedziami.','Za pierwszym razem ustal sens, za drugim potwierdź szczegół.','Nie wybieraj odpowiedzi tylko dlatego, że słyszysz identyczne słowo.'],'Pułapka: nagranie często najpierw wspomina błędną opcję, a dopiero potem ją koryguje.'],
 ['Czytanie',['Najpierw przeczytaj pytania.','Szukaj parafrazy, nie kopii słów.','Ustal funkcję akapitu: przykład, kontrast, przyczyna, opinia.','Po wyborze wskaż konkretne zdanie będące dowodem.'],'Pułapka: odpowiedź może być prawdziwa ogólnie, ale nie wynikać z tekstu.'],
 ['Środki językowe',['Rozpoznaj, czego wymaga luka: czasu, przyimka, formy słowa czy kolokacji.','Sprawdź słowa po obu stronach luki.','Zachowaj znaczenie w transformacji.','Na końcu przeczytaj całe zdanie.'],'Pułapka: poprawna gramatyka nie wystarcza, jeśli zmieniłeś sens zdania.'],
 ['Pisanie',['Zakreśl wszystkie elementy polecenia.','Zaplanuj osobny fragment do każdego punktu.','Każdy punkt rozwiń: fakt + szczegół/przyczyna/przykład.','Zostaw czas na limit słów i korektę.'],'Pułapka: samo wspomnienie punktu nie jest jego rozwinięciem.'],
 ['Ustna',['Reaguj na rozmówcę i dopytuj w rozmowie.','Opis obrazka oprzyj na: who, where, what, atmosphere.','W wyborze uzasadnij wybór i odrzuć pozostałe opcje.','Gdy brakuje słowa, parafrazuj zamiast milczeć.'],'Pułapka: lista pojedynczych zdań bez rozwinięcia obniża komunikatywność.']
];
const GRAMMAR=[
 ['Szyk zdania','S + V + O + miejsce + czas'],['be / have / do','operatory pytań i przeczeń'],['Present Simple / Continuous','rutyna kontra teraz'],['Past Simple / Continuous','zdarzenie kontra tło'],['Present Perfect','have/has + V3'],['Past Perfect','had + V3'],['Future forms','will / going to / continuous / simple'],['Modal verbs','can, must, should, may + V1'],['Passive','be + V3'],['Reported speech','said/told + zmiana perspektywy'],['Conditionals 0–III','fakt, realność, hipoteza, przeszłość'],['Gerund / infinitive','doing kontra to do'],['Articles & quantifiers','a/an/the; much/many/few/little'],['Relative clauses','who/which/that/whose'],['Word formation','prefix + rdzeń + suffix'],['Advanced B2/C1','modal perfect, mixed, wish, inversion, causative']
];
const QUESTIONS=[
 ['I ___ from Poland.',['am','is','are'],'am'],['She ___ coffee every morning.',['drink','drinks','is drink'],'drinks'],['Look! It ___.',['rains','is raining','rain'],'is raining'],['We ___ London last year.',['visit','visited','have visit'],'visited'],['I have lived here ___ 2022.',['for','since','from'],'since'],['If it rains, we ___ at home.',['stay','will stay','would stayed'],'will stay'],['The book ___ by Orwell.',['wrote','was written','is write'],'was written'],['He said that he ___ tired.',['is','was','has'],'was'],['I enjoy ___ English.',['learn','learning','to learning'],'learning'],['This is the girl ___ won.',['which','who','where'],'who'],['You ___ have called me; I was worried.',['should','can','need'],'should'],['If I had known, I ___ helped.',['will have','would have','had'],'would have'],['She denied ___ the message.',['send','sending','to send'],'sending'],['Never ___ such a view.',['I saw','have I seen','I have seen'],'have I seen'],['The proposal needs ___.',['discuss','discussing','discussed'],'discussing']
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const section=(id,title,lead,body)=>`<section class="section" id="${id}"><div class="sectionhead"><h1>${title}</h1><p>${lead}</p></div>${body}</section>`;
function build(){const main=document.querySelector('#content')||document.querySelector('.main'),footer=document.querySelector('.main .footer');if(!main||document.querySelector('#eng-path'))return;
 const path=section('eng-path','Ścieżka od A0 do matury','Nie zaczynaj od losowych arkuszy. Wybierz poziom startowy, opanuj wymagane umiejętności i dopiero wtedy przejdź dalej.',`<div class="eng-dashboard">${LEVELS.map((l,i)=>`<article class="eng-level"><strong>${l[0]}</strong><h3>${l[1]}</h3><p>${l[2]}</p><label><input class="progressCheck" data-key="eng-level-${i}" type="checkbox"> etap opanowany</label></article>`).join('')}</div><div class="eng-callout"><div><b>Nie znasz swojego poziomu?</b><p>Test poniżej sprawdza rosnącą trudność konstrukcji od A0 do C1.</p></div><button class="btn primary" data-go="eng-diagnostic">Zrób test startowy</button></div>`);
 const strategy=section('eng-strategy','Strategie wszystkich części egzaminu','Każdy typ zadania ma powtarzalny algorytm. Naucz się procesu, a nie pojedynczych odpowiedzi.',`<div class="eng-skill-grid">${STRATEGIES.map((s,i)=>`<article class="eng-skill"><div class="eng-skill-head"><span class="eng-skill-num">${i+1}</span><div><h3>${s[0]}</h3><span class="mini">procedura krok po kroku</span></div></div><ol>${s[1].map(x=>`<li>${x}</li>`).join('')}</ol><details><summary>Najczęstsza pułapka</summary><p>${s[2]}</p></details></article>`).join('')}</div>`);
 const grammar=section('eng-grammar-map','Mapa gramatyki A0–C1','Ta mapa pokazuje cały zakres w kolejności nauki. Szczegółowe lekcje i przykłady pozostają w działach gramatycznych podstawy i rozszerzenia.',`<div class="eng-grammar-index">${GRAMMAR.map((g,i)=>`<article class="eng-grammar-card"><h3>${i+1}. ${g[0]}</h3><code>${g[1]}</code><label class="checkline"><input class="progressCheck" data-key="eng-grammar-${i}" type="checkbox"> umiem użyć w zdaniu</label></article>`).join('')}</div>`);
 const diag=section('eng-diagnostic','Test poziomujący A0–C1','15 pytań rosnących poziomem. Wynik wskazuje punkt startowy, ale nie jest certyfikatem językowym.',`<form class="eng-diagnostic" id="engDiagnostic">${QUESTIONS.map((q,i)=>`<fieldset class="eng-diag-q"><legend>${i+1}. ${q[0]}</legend>${q[1].map(a=>`<label><input type="radio" name="ed-${i}" value="${esc(a)}"> ${esc(a)}</label>`).join('')}</fieldset>`).join('')}<button class="btn primary" type="button" id="engCheckDiagnostic">Sprawdź wynik i plan</button></form><div class="eng-result" id="engDiagnosticResult"></div>`);
 const writing=section('eng-workbench','Laboratorium pisania','Pisz bez wychodzenia ze strony. Tekst i checklisty zapisują się automatycznie na tym urządzeniu.',`<div class="eng-workbench"><article class="eng-editor"><h3>Podstawa · 100–150 słów</h3><p>Napisz wiadomość o wydarzeniu szkolnym. Opisz wydarzenie, swoją rolę, problem i poproś odbiorcę o pomoc.</p><textarea data-eng-pad="basic" placeholder="Hi Alex,&#10;&#10;Guess what happened at school..."></textarea><div class="eng-counter"><span>Cel CKE: 100–150</span><b data-eng-count="basic">0 słów</b></div></article><article class="eng-editor"><h3>Rozszerzenie · 200–250 słów</h3><p>Napisz rozprawkę: Czy szkoły powinny ograniczyć używanie telefonów podczas lekcji? Omów skutki edukacyjne i społeczne.</p><textarea data-eng-pad="extended" placeholder="Nowadays, the use of smartphones at school..."></textarea><div class="eng-counter"><span>Cel CKE: 200–250</span><b data-eng-count="extended">0 słów</b></div></article></div><div class="eng-checks">${['Odpowiedziałem na wszystkie elementy polecenia','Każdy punkt rozwinąłem szczegółem lub przykładem','Tekst ma logiczne akapity','Użyłem łączników, ale nie przesadziłem','Sprawdziłem czasy, szyk i zgodność','Mieszczę się w limicie słów'].map((x,i)=>`<label><input class="progressCheck" data-key="eng-write-check-${i}" type="checkbox"><span>${x}</span></label>`).join('')}</div>`);
 [path,strategy,grammar,diag,writing].forEach(html=>main.insertAdjacentHTML('beforeend',html));addNav();bind();if(typeof loadProgress==='function')loadProgress();}
function addNav(){const nav=document.querySelector('#nav');if(!nav)return;const box=document.createElement('div');box.className='navgroup eng-master-nav';box.innerHTML='<div class="navtitle">PEŁNA ŚCIEŻKA <span>A0–C1</span></div>'+[['eng-path','Poziomy A0–C1'],['eng-diagnostic','Test poziomujący'],['eng-grammar-map','Mapa gramatyki'],['eng-strategy','Strategie egzaminu'],['eng-workbench','Laboratorium pisania']].map(x=>`<button class="navbtn" data-go="${x[0]}">${x[1]}</button>`).join('');nav.prepend(box);const mobile=document.querySelector('#mobileNav');if(mobile)[...box.querySelectorAll('[data-go]')].forEach(b=>mobile.insertAdjacentHTML('beforeend',`<option value="${b.dataset.go}">PEŁNA ŚCIEŻKA — ${b.textContent}</option>`));}
function bind(){document.querySelector('#engCheckDiagnostic')?.addEventListener('click',()=>{let score=0,answered=0;QUESTIONS.forEach((q,i)=>{const a=document.querySelector(`input[name="ed-${i}"]:checked`);if(a){answered++;if(a.value===q[2])score++;}});const level=score<=2?'A0':score<=5?'A1':score<=8?'A2':score<=11?'B1':score<=13?'B2':'C1',advice={A0:'zacznij od „Angielski od absolutnych podstaw”',A1:'utrwal fundamenty, pytania i pierwsze czasy',A2:'dokończ gramatykę podstawową i słownictwo 14 tematów',B1:'pracuj regularnie z formatem matury podstawowej',B2:'przejdź do transformacji, kolokacji i pisania rozszerzonego',C1:'utrzymuj poziom pełnymi arkuszami i analizą błędów'}[level],box=document.querySelector('#engDiagnosticResult');box.innerHTML=`<h3>${score}/15 · orientacyjnie ${level}</h3><p>Odpowiedziano: ${answered}/15. Rekomendacja: <b>${advice}</b>.</p><p class="mini">Wynik jest orientacyjny. O poziomie decydują także słuchanie, czytanie, pisanie i mówienie.</p>`;box.classList.add('show');box.scrollIntoView({behavior:'smooth',block:'nearest'});});document.querySelectorAll('[data-eng-pad]').forEach(area=>{const key='eng-pad-'+area.dataset.engPad;area.value=localStorage.getItem(key)||'';const update=()=>{localStorage.setItem(key,area.value);const n=area.value.trim()?area.value.trim().split(/\s+/).length:0,c=document.querySelector(`[data-eng-count="${area.dataset.engPad}"]`),ok=area.dataset.engPad==='basic'?n>=100&&n<=150:n>=200&&n<=250;c.textContent=n+' słów';c.classList.toggle('ok',ok)};area.addEventListener('input',update);update()});setTimeout(()=>{const v=document.querySelector('.eng-version');if(v)v.textContent='Wersja 3.4.3 • wspólny system dostępu';},0)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',build):build();
})();
