window.POLISH_EXAM = {
  title:'Próbna matura podstawowa 2027 – arkusz treningowy nr 1',
  duration:240,
  maxPoints:60,
  sourceUrl:'https://bip.cke.gov.pl/artykul/211/1659/egzamin-maturalny-w-formule-2023',
  texts:[
    {id:'A',title:'Tekst A. Pamięć jako rekonstrukcja',body:`Pamięć nie działa jak magazyn, z którego wyjmujemy nienaruszone obrazy przeszłości. Każde przypomnienie jest ponownym składaniem wydarzenia z zachowanych szczegółów, późniejszej wiedzy i aktualnych emocji. Dlatego dwie osoby uczestniczące w tej samej sytuacji mogą opowiedzieć ją inaczej, nie próbując świadomie kłamać. Nie oznacza to jednak, że wszystkie wspomnienia są równie prawdziwe. Można je porównywać z dokumentami, relacjami innych ludzi i konsekwencjami zdarzeń. Dojrzałe pamiętanie wymaga więc podwójnej uczciwości: wierności temu, co udało się zachować, oraz świadomości, że własna perspektywa pozostaje ograniczona.`},
    {id:'B',title:'Tekst B. Wspólnota potrzebuje opowieści',body:`Wspólnota istnieje nie tylko dzięki instytucjom, lecz także dzięki opowieściom o wydarzeniach uznawanych za ważne. Rocznice, rodzinne historie i dzieła literackie tworzą język, w którym ludzie opisują swoje pochodzenie. Taka pamięć może łączyć, ale bywa również używana do wykluczania tych, którzy nie pasują do wygodnego obrazu przeszłości. Odpowiedzialna wspólnota nie powinna usuwać trudnych faktów. Musi dopuszczać wiele świadectw i pytać, dlaczego poszczególne grupy zapamiętały to samo wydarzenie odmiennie. Dopiero rozmowa między perspektywami pozwala przekształcić pamięć w narzędzie rozumienia, a nie w broń.`}
  ],
  sections:[
    {title:'Część 1. Język polski w użyciu',max:15,tasks:[
      {id:'e1',points:1,type:'choice',question:'Które stwierdzenie najtrafniej oddaje główną myśl tekstu A?',options:['Pamięć wiernie przechowuje wszystkie wydarzenia.','Wspomnienie jest rekonstrukcją, którą należy świadomie weryfikować.','Dokumenty zawsze są ważniejsze niż ludzkie relacje.','Emocje uniemożliwiają poznanie przeszłości.'],answer:1,explain:'Autor przedstawia pamięć jako rekonstrukcję i wskazuje potrzebę porównywania wspomnień z innymi źródłami.'},
      {id:'e2',points:2,type:'choice',question:'Jaka relacja łączy oba teksty?',options:['Tekst B całkowicie zaprzecza tekstowi A.','Tekst A dotyczy jednostki, a tekst B rozwija problem na poziomie wspólnoty.','Oba teksty opisują wyłącznie biologiczne mechanizmy pamięci.','Tekst A jest instrukcją, a tekst B jej streszczeniem.'],answer:1,explain:'Pierwszy tekst omawia pamięć jednostkową, drugi – zbiorową; oba podkreślają wielość perspektyw i odpowiedzialność.'},
      {id:'e3',points:2,type:'open',question:'Wyjaśnij własnymi słowami, na czym polega „podwójna uczciwość” pamiętania w tekście A.',rubric:'1 pkt za wierność zachowanym faktom; 1 pkt za świadomość ograniczenia własnej perspektywy.'},
      {id:'e4',points:2,type:'open',question:'Wyjaśnij sens metafory „pamięć jako broń” użytej w tekście B.',rubric:'Odpowiedź powinna wskazać manipulowanie pamięcią w celu wykluczania, dzielenia ludzi lub narzucania wygodnej wersji przeszłości.'},
      {id:'e5',points:3,type:'open',question:'Sformułuj jeden wspólny wniosek wynikający z obu tekstów i uzasadnij go, odwołując się do każdego autora.',rubric:'1 pkt za trafny wspólny wniosek; po 1 pkt za funkcjonalne odwołanie do tekstu A i B.'},
      {id:'e6',points:5,type:'open',question:'Napisz notatkę syntetyzującą na temat: „Pamięć a prawda o przeszłości”. Twoja wypowiedź powinna mieć 60–90 słów.',rubric:'Oceniane: przedstawienie stanowisk obu tekstów, zestawienie ich relacji, spójność, język oraz zachowanie 60–90 słów.'}
    ]},
    {title:'Część 2. Test historycznoliteracki',max:15,tasks:[
      {id:'e7',points:2,type:'choice',question:'Wskaż prawidłową kolejność epok.',options:['renesans → antyk → romantyzm → pozytywizm','antyk → średniowiecze → renesans → romantyzm','średniowiecze → antyk → pozytywizm → romantyzm','antyk → renesans → średniowiecze → pozytywizm'],answer:1,explain:'Antyk poprzedza średniowiecze, następnie występuje renesans, a w Polsce romantyzm rozpoczyna się w 1822 roku.'},
      {id:'e8',points:2,type:'choice',question:'Który zestaw poprawnie łączy bohatera z jego celem?',options:['Antygona – zdobycie tronu; Wokulski – obrona Teb','Konrad – rząd dusz i ocalenie narodu; Rieux – walka z epidemią','Makbet – godny pochówek brata; Cezary – obrona Jasnej Góry','Kmicic – miłość do Izabeli; Winston – odzyskanie Soplicowa'],answer:1,explain:'Konrad chce otrzymać moc ocalenia narodu, a doktor Rieux konsekwentnie walczy z dżumą.'},
      {id:'e9',points:2,type:'open',question:'Wyjaśnij, dlaczego konflikt Antygony i Kreona jest konfliktem tragicznym.',rubric:'Trzeba wskazać zderzenie równorzędnych racji – prawa boskiego/rodzinnego i państwowego – oraz to, że każdy wybór prowadzi do straty.'},
      {id:'e10',points:2,type:'open',question:'Jaką funkcję pełni symbol lawy w „Dziadach cz. III”?',rubric:'Lawa symbolizuje naród: zimna i twarda skorupa oznacza elity/oportunistów, a gorące wnętrze – patriotyczną młodzież i ukrytą siłę.'},
      {id:'e11',points:1,type:'choice',question:'Który utwór jest powieścią-parabolą?',options:['„Lalka”','„Dżuma”','„Antygona”','„Wesele”'],answer:1,explain:'„Dżuma” ma sens dosłowny – epidemię – oraz uniwersalny: model walki człowieka ze złem.'},
      {id:'e12',points:2,type:'open',question:'Wyjaśnij różnicę między symbolem a alegorią i podaj po jednym przykładzie.',rubric:'Symbol jest wieloznaczny, alegoria ma znaczenie utrwalone. Przykłady: chochoł/złoty róg oraz kostucha jako alegoria śmierci.'},
      {id:'e13',points:2,type:'choice',question:'Który bohater przechodzi przemianę od porywczego szlachcica do pokornego emisariusza służącego ojczyźnie?',options:['Stanisław Wokulski','Jacek Soplica','Rodion Raskolnikow','Artur'],answer:1,explain:'Jacek Soplica przyjmuje tożsamość księdza Robaka i odkupuje dawną winę służbą ojczyźnie.'},
      {id:'e14',points:2,type:'open',question:'Porównaj stosunek do norm społecznych w „Antygonie” i „Tangu”. Sformułuj jeden wniosek.',rubric:'Antygona odrzuca prawo państwowe w obronie wyższego ładu; Artur chce przywrócić normy po anarchii. Wniosek powinien dotyczyć funkcji zasad i odpowiedzialności.'}
    ]}
  ],
  essay:{id:'e15',points:30,minWords:300,topics:['Człowiek wobec utraty – jakie postawy może przyjąć?','Czy jednostka ma obowiązek sprzeciwić się niesprawiedliwemu porządkowi?'],requirements:'Wybierz jeden temat. Odwołaj się do lektury obowiązkowej, innego utworu literackiego oraz co najmniej dwóch kontekstów. Napisz minimum 300 słów.',rubric:'Oceń: spełnienie formalnych warunków polecenia, kompetencje literackie i kulturowe, kompozycję, spójność, styl, język, ortografię oraz interpunkcję.'}
};
