window.MATURA_EXPANDED = {
  shortWorks: [
    {t:'Biblia – najważniejsze księgi i opowieści',a:'autorzy różnych epok; Stary i Nowy Testament',m:'starożytność • tekst święty, zbiór wielu gatunków',p:'Księga Rodzaju przedstawia stworzenie świata, grzech pierwszych ludzi, Kaina i Abla, potop oraz dzieje patriarchów. Księga Hioba pokazuje próbę człowieka sprawiedliwego, który traci rodzinę, majątek i zdrowie, choć nie zawinił. Kohelet rozważa przemijanie i marność ludzkich wysiłków. Psalmy są modlitwami pochwalnymi, błagalnymi i dziękczynnymi. Ewangelie opowiadają o nauczaniu, śmierci i zmartwychwstaniu Chrystusa, a Apokalipsa przedstawia symboliczną walkę dobra ze złem i zapowiedź odnowienia świata.',h:'Hiob – człowiek niewinnie cierpiący, który spiera się z Bogiem, ale nie porzuca relacji z Nim. Kohelet – mędrzec szukający trwałego sensu. Kain – bratobójca uciekający od odpowiedzialności. Chrystus – wzór miłości ofiarnej, przebaczenia i poświęcenia.',m2:'stworzenie, raj i utrata niewinności, bratobójstwo, cierpienie niezawinione, próba wiary, vanitas, wędrówka, ofiara, apokalipsa, odkupienie',m3:'Biblia pokazuje człowieka jako istotę wolną, lecz odpowiedzialną za wybory. Nie daje jednej prostej odpowiedzi na cierpienie: Hiob odzyskuje więź z Bogiem, ale tajemnica zła pozostaje. To podstawowy kontekst do „Trenów”, „Dziadów III”, „Zbrodni i kary”, „Innego świata” i literatury wojennej.'},
    {t:'Iliada',a:'Homer',m:'antyk • epos bohaterski',p:'Utwór obejmuje krótki fragment wojny trojańskiej, a jego osią jest gniew Achillesa. Obrażony przez Agamemnona heros wycofuje się z walki. Trojanie zyskują przewagę, a Patrokl wkłada zbroję Achillesa i ginie z ręki Hektora. Achilles wraca, zabija Hektora i bezcześci jego ciało. Dopiero błaganie starego Priama przywraca mu współczucie; wydaje zwłoki ojcu, aby mogły zostać pochowane.',h:'Achilles wybiera sławę i krótkie życie, ale gniew odbiera mu umiar; po spotkaniu z Priamem odzyskuje człowieczeństwo. Hektor walczy z obowiązku wobec Troi i rodziny, choć przeczuwa klęskę. Priam ryzykuje życie, aby ocalić godność zmarłego syna.',m2:'wojna, honor, sława, gniew, zemsta, fatum, śmierć, rodzina, godność pokonanego, humanizm',m3:'Najważniejsze nie jest zwycięstwo, lecz przemiana Achillesa: wspólne doświadczenie straty łączy wrogów. Użyj przy tematach o wojnie, człowieczeństwie, emocjach, przeznaczeniu i godnym pochówku – zwłaszcza obok „Antygony”.'},
    {t:'Lament świętokrzyski',a:'autor anonimowy',m:'średniowiecze • plankt, lament',p:'Maryja stojąca pod krzyżem zwraca się do ludzi, umierającego Jezusa i archanioła Gabriela. Nie przemawia jak dostojna Królowa Nieba, ale jak bezradna matka, która chciałaby przejąć cierpienie syna. Prosi inne matki, by modliły się o uniknięcie podobnej tragedii.',h:'Podmiotem lirycznym jest Maryja. Jej monolog buduje obraz mater dolorosa – matki cierpiącej. Adresatami są ludzie, Jezus, Gabriel i wszystkie matki.',m2:'ból matki, śmierć dziecka, cierpienie, miłość rodzicielska, samotność, sacrum i człowieczeństwo',m3:'Utwór humanizuje postać biblijną i pozwala odbiorcy współodczuwać. Zestaw z „Trenami”: oba teksty pokazują rozpacz rodzica, ale Kochanowski mówi jako ojciec przeżywający kryzys filozoficzny.'},
    {t:'Rozmowa Mistrza Polikarpa ze Śmiercią',a:'autor anonimowy',m:'średniowiecze • dialog, poemat dydaktyczny',p:'Uczony Polikarp prosi Boga, aby mógł zobaczyć Śmierć. Ukazuje mu się odrażająca, rozkładająca się kobieta z kosą. Wyjaśnia, że dosięga każdego bez względu na stan i majątek, a następnie satyrycznie wylicza grzechy duchownych, sędziów, lekarzy, karczmarzy i innych grup.',h:'Polikarp reprezentuje człowieka poszukującego wiedzy o kresie życia. Śmierć jest spersonifikowana, groteskowa, wszechmocna i bezlitośnie demaskuje ludzką pychę.',m2:'danse macabre, memento mori, równość wobec śmierci, rozkład ciała, krytyka stanów, vanitas, groteska',m3:'Śmierć unieważnia społeczne hierarchie, a komizm służy moralnej przestrodze. Dobry kontekst do barokowego vanitas, „Trenów”, „Dżumy” i literatury wojennej.'},
    {t:'Pieśń o Rolandzie',a:'autor anonimowy',m:'średniowiecze • chanson de geste, epos rycerski',p:'Podczas odwrotu wojsk Karola Wielkiego tylna straż dowodzona przez Rolanda zostaje zaatakowana. Roland z dumy zbyt długo nie chce zadąć w róg i wezwać pomocy. Gdy robi to później, jego oddział jest skazany na zagładę. Bohater próbuje zniszczyć miecz Durendal, modli się i umiera zwrócony ku wrogom. Karol mści poległych.',h:'Roland jest wzorem rycerza: odważny, wierny Bogu, władcy i ojczyźnie. Jednocześnie jego duma prowadzi do niepotrzebnych ofiar. Oliwier reprezentuje rozsądek i odpowiedzialność za wspólnotę.',m2:'etos rycerski, honor, wierność, patriotyzm, śmierć, poświęcenie, pycha, ars moriendi',m3:'Utwór buduje parenetyczny wzorzec, ale pozwala pytać o granicę między heroizmem a brawurą. Porównaj z Hektorem, Kmicicem albo powstańcami z literatury wojennej.'},
    {t:'Romantyczność i wybrane ballady',a:'Adam Mickiewicz',m:'romantyzm • ballada',p:'W „Romantyczności” Karusia widzi zmarłego Jasia i rozmawia z nim. Lud wierzy dziewczynie, natomiast Starzec uznaje jej przeżycie za zabobon. Narrator staje po stronie „czucia i wiary”. W „Świteziance” niewierny strzelec zostaje ukarany przez nimfę, a w „Lilijach” zabójczyni męża nie unika kary mimo prób ukrycia winy.',h:'Karusia jest samotna w rozpaczy, lecz wspólnota ludu uznaje jej doświadczenie. Starzec reprezentuje oświeceniowy racjonalizm. Narrator formułuje romantyczny program poznania.',m2:'irracjonalizm, ludowość, miłość silniejsza niż śmierć, natura, wina i kara, prawdy żywe, konflikt pokoleń',m3:'Ballady zakładają istnienie pozarozumowego ładu moralnego: zbrodnia zostaje ukarana, a natura uczestniczy w sądzie. „Romantyczność” jest manifestem przełomu romantycznego i świetnym kontekstem do sporu rozumu z wiarą.'},
    {t:'Wybrana satyra Ignacego Krasickiego',a:'Ignacy Krasicki',m:'oświecenie • satyra',p:'W „Pijaństwie” szlachcic szczegółowo opisuje kolejne okazje do picia, jednocześnie deklarując potępienie nałogu. Rozmowa obnaża brak samokontroli i narodową skłonność do usprawiedliwiania wad. „Żona modna” pokazuje małżeństwo zawarte dla posagu, które prowadzi do ruiny przez bezmyślne naśladowanie cudzoziemskiej mody.',h:'Bohater satyry jest typem społecznym, nie pogłębioną jednostką. Kompromituje się własnymi słowami; czytelnik rozpoznaje mechanizm racjonalizacji i hipokryzję.',m2:'pijaństwo, moda, małżeństwo dla pieniędzy, hipokryzja, krytyka szlachty, dydaktyzm, ironia',m3:'Śmiech ma poprawiać obyczaje. Krasicki nie atakuje jednej osoby, tylko powszechną wadę. Użyj jako kontekstu do „Skąpca”, „Wesela” albo tematów o pieniądzu, pozorach i odpowiedzialności społecznej.'},
    {t:'Ferdydurke',a:'Witold Gombrowicz',m:'dwudziestolecie • powieść groteskowa',p:'Trzydziestoletni Józio zostaje „upupiony” przez profesora Pimkę i cofnięty do szkoły. Trafia potem do nowoczesnych Młodziaków, których demaskuje, aranżując kompromitujące spotkanie Zuty. Ucieka z Miętusem do dworku Hurleckich, gdzie próba bratania się z parobkiem kończy się chaosem. Józio ucieka z Zosią, lecz rozumie, że każda ucieczka prowadzi do kolejnej formy.',h:'Józio chce osiągnąć autentyczność, ale inni nieustannie narzucają mu „gębę”. Pimko jest producentem niedojrzałości; Miętus obsesyjnie chce przełamać hierarchię; Młodziakowie grają rolę nowoczesnych.',m2:'forma, gęba, pupa, niedojrzałość, szkoła, presja społeczna, autentyczność, groteska, konflikt pokoleń',m3:'Nie istnieje czyste „ja” poza relacjami, lecz można być świadomym narzucanych form. To uniwersalny kontekst do jednostki wobec społeczeństwa, dojrzewania, konwenansu i buntu.'},
    {t:'Proszę państwa do gazu',a:'Tadeusz Borowski',m:'literatura wojenna • opowiadanie obozowe',p:'Tadek pracuje przy rozładowywaniu transportu do Auschwitz. Więźniowie zabierają bagaże przywiezionych, a większość nowo przybyłych zostaje skierowana do komór gazowych. Narracja jest chłodna i pozbawiona patosu; codzienny język zderza się z masową zbrodnią.',h:'Tadek jest więźniem przystosowanym do reguł obozu. Nie jest prostym portretem autora, lecz figurą człowieka zlagrowanego, który przeżywa dzięki uczestnictwu w systemie i ograniczeniu empatii.',m2:'Zagłada, dehumanizacja, człowiek zlagrowany, głód, moralność w sytuacji granicznej, uprzedmiotowienie, obojętność',m3:'Obóz niszczy tradycyjne kryteria moralne i wciąga ofiary w mechanizm przemocy. Porównaj z „Innym światem”: Herling broni istnienia wartości, Borowski mocniej pokazuje przystosowanie do odwróconych norm.'},
    {t:'Górą „Edek”',a:'Marek Nowakowski',m:'współczesność • opowiadanie',p:'W codziennej sytuacji drogowej kierowca eleganckiego samochodu zostaje pokonany przez agresywnego właściciela ciężkiego pojazdu. Tytułowe nawiązanie do Edka z „Tanga” rozszerza drobny konflikt do diagnozy świata, w którym racja przegrywa z siłą i bezczelnością.',h:'„Edek” nie musi być tą samą postacią co u Mrożka – to typ człowieka prymitywnego, skutecznego dzięki przemocy i lekceważeniu zasad.',m2:'siła, przemoc, chamstwo, konflikt społeczny, intertekstualność, kryzys norm, zwycięstwo prymitywizmu',m3:'Nawiązanie do „Tanga” jest kluczem interpretacyjnym. Pokazuje, że finał dramatu Mrożka powtarza się w zwykłym życiu: próżnię norm zajmuje brutalna skuteczność.'},
    {t:'Miejsce',a:'Andrzej Stasiuk',m:'współczesność • opowiadanie',p:'Narrator wraca do miejsca po rozebranej cerkwi. Budynku już nie ma, ale ślady w krajobrazie, pamięć mieszkańców i wyobraźnia pozwalają odtworzyć jego istnienie. Nieobecność staje się bardziej znacząca niż materialny obiekt.',h:'Narrator jest obserwatorem i strażnikiem pamięci. Próbuje zrozumieć przestrzeń, która przechowuje historię ludzi wysiedlonych i kultury zanikającej.',m2:'miejsce, pamięć, utrata, pogranicze, dom, przemijanie, sacrum, ślad, tożsamość',m3:'Miejsce nie jest tylko punktem geograficznym – tworzą je pamięć, ludzie i opowieść. Łącz z Soplicowem, Nawłocią, Warszawą z „Lalki” oraz tematami o małej ojczyźnie.'},
    {t:'Profesor Andrews w Warszawie',a:'Olga Tokarczuk',m:'współczesność • opowiadanie',p:'Brytyjski profesor przyjeżdża do Warszawy tuż przed wprowadzeniem stanu wojennego. Traci kontakt z osobami, które miały się nim opiekować. Nie zna polskiego ani realiów, więc puste ulice, wojsko, kolejki i brak informacji odbiera jak niezrozumiały, niemal fantastyczny świat.',h:'Andrews jest obcym pozbawionym języka i kodu kulturowego. Jego zagubienie pozwala zobaczyć znaną Polakom rzeczywistość z dystansu.',m2:'obcość, samotność, język, stan wojenny, absurd, komunikacja, perspektywa cudzoziemca, zagubienie',m3:'Zmiana punktu widzenia ujawnia absurd systemu. Utwór wykorzystaj przy narracji, obcości, komunikacji, totalitaryzmie i wpływie historii na jednostkę.'},
    {t:'Podróże z Herodotem',a:'Ryszard Kapuściński',m:'współczesność • reportaż autobiograficzny',p:'Młody reporter wyjeżdża pierwszy raz za granicę, początkowo do Indii i Chin. Towarzyszą mu „Dzieje” Herodota. Własne doświadczenia zestawia z podróżami starożytnego historyka, ucząc się obserwacji, pokory wobec innych kultur i znaczenia języka.',h:'Narrator dojrzewa jako reporter. Z człowieka niepewnego i ograniczonego przez własne doświadczenie staje się uważnym pośrednikiem między kulturami. Herodot jest jego symbolicznym mistrzem.',m2:'podróż, poznanie, obcość, kultura, język, mistrz, ciekawość, dojrzewanie, reportaż',m3:'Podróż zmienia patrzącego, nie jest tylko przemieszczaniem się. Użyj do motywu drogi, spotkania z Innym, edukacji oraz odpowiedzialności reportera.'}
  ],
  poems: [
    ['Bogurodzica','anonim','średniowiecze','Zbiorowy podmiot zwraca się do Maryi i Jana Chrzciciela, prosząc Chrystusa o dobre życie i zbawienie.','modlitwa wspólnoty; adresat: Maryja, Chrystus i Jan Chrzciciel','apostrofy, paralelizmy, archaizmy, refren „Kyrie eleison” – nadają uroczysty i wspólnotowy charakter','teocentryzm, deesis, pośrednictwo, wspólnota','„Pieśń o Rolandzie”; średniowieczny uniwersalizm'],
    ['Pieśń IX, księgi I','Jan Kochanowski','renesans','Człowiek powinien korzystać z życia, ale zachować umiar i spokój wobec zmiennej Fortuny.','mędrzec udzielający rad wspólnocie','apostrofy, sentencje, personifikacja Fortuny, regularność – budują ton ładu','stoicyzm połączony z epikureizmem; złoty środek','„Treny” jako kryzys wcześniejszej pewności'],
    ['Pieśń V, księgi II','Jan Kochanowski','renesans','Poeta opisuje spustoszenie Podola przez Tatarów i wzywa szlachtę do finansowania obrony państwa.','obywatel upominający rodaków','apostrofa, pytania retoryczne, wykrzyknienia, ironiczna puenta – mobilizują i zawstydzają','patriotyzm, odpowiedzialność obywatelska, zagrożenie ojczyzny','„Hymn do miłości ojczyzny”, „Dziady III”'],
    ['Psalm 13','Jan Kochanowski – parafraza','renesans','Człowiek opuszczony prosi Boga o pomoc i odzyskuje ufność mimo cierpienia.','wierzący w sytuacji próby; adresat: Bóg','anafora pytań „dokąd”, apostrofy, kontrast rozpaczy i nadziei','cierpienie, modlitwa, kryzys i odbudowa wiary','Księga Hioba, „Treny”'],
    ['Psalm 47','Jan Kochanowski – parafraza','renesans','Hymniczna pochwała Boga jako władcy świata i źródła ładu.','zbiorowy podmiot zachęcający narody do uwielbienia','tryb rozkazujący, wykrzyknienia, epitety, paralelizmy – wzmacniają podniosłość','Bóg, harmonia, wspólnota, pochwała','„Bogurodzica”; hymn jako gatunek'],
    ['Hymn do miłości ojczyzny','Ignacy Krasicki','oświecenie','Miłość ojczyzny uszlachetnia i pozwala przyjąć rany, niewolę, a nawet śmierć.','patriota przemawiający do wspólnoty','apostrofa, anafora, paradoksy „smakują trucizny” – pokazują cenę oddania','patriotyzm, poświęcenie, wolność','„Pieśń o Rolandzie”, „Dziady III”'],
    ['Oda do młodości','Adam Mickiewicz','romantyzm','Młodość i wspólnota mają przekroczyć egoizm starego świata i stworzyć nową rzeczywistość.','przywódca pokolenia; adresat: młodość i młodzi','apostrofy, wykrzyknienia, hiperbole, kontrast stare–młode, metafory lotu i światła','bunt pokoleniowy, wspólnota, idealizm, przemiana świata','„Romantyczność”; spór klasyków z romantykami'],
    ['Grób Agamemnona – fragment','Juliusz Słowacki','romantyzm','Wizyta w grobowcu prowadzi poetę do rozrachunku z Polską po klęsce powstania listopadowego.','poeta-patriota i surowy sędzia narodu','apostrofy, symbole Termopil i Cheronei, kontrast, ironia – budują gorzką diagnozę','klęska, patriotyzm, odpowiedzialność narodu, poeta','„Wesele”, „Dziady III”'],
    ['Testament mój','Juliusz Słowacki','romantyzm','Poeta podsumowuje samotne życie i przekazuje następnym pokoleniom obowiązek służby ojczyźnie.','poeta świadomy śmierci; adresat: przyjaciele i przyszli spadkobiercy idei','metafory, nakazy, symbole sternika i pochodni, ton testamentu','artysta, nieśmiertelność dzieła, poświęcenie, ojczyzna','Horacy „Exegi monumentum”; romantyczny poeta-wieszcz'],
    ['Traktat moralny – fragmenty','Czesław Miłosz','współczesność','Poeta wzywa do samodzielnego myślenia i odpowiedzialności w epoce ideologii oraz uproszczonych sądów.','intelektualista mówiący do współczesnego człowieka','ironia, aforyzmy, bezpośrednie zwroty, dyskursywność – łączą poezję z rozumowaniem','odpowiedzialność, prawda, historia, jednostka wobec ideologii','„Rok 1984”, doświadczenie totalitaryzmów'],
    ['Lament świętokrzyski','anonim','średniowiecze','Maryja opłakuje mękę i śmierć Jezusa jako bezradna matka.','Maryja; adresaci: ludzie, Syn, Gabriel i matki','apostrofy, zdrobnienia, wykrzyknienia, paralelizmy – humanizują sacrum','cierpienie matki, śmierć dziecka, miłość','„Treny” Kochanowskiego']
  ],
  philosophies: [
    ['Stoicyzm','Zenon z Kition, Seneka, Marek Aureliusz','Szczęście daje cnota, rozum i panowanie nad reakcją; trzeba odróżnić to, na co mamy wpływ, od tego, czego nie kontrolujemy.','Kochanowski w pieśniach głosi równowagę, a w „Trenach” sprawdza jej granice.'],
    ['Epikureizm','Epikur','Szczęście to brak cierpienia i lęku, umiar, przyjaźń oraz spokojne korzystanie z chwili – nie nieograniczona przyjemność.','Pieśni Kochanowskiego: radość życia połączona z umiarem.'],
    ['Platonizm','Platon','Rzeczywistość zmysłowa jest niedoskonałym odbiciem świata idei; poznanie prowadzi od pozoru ku prawdzie.','Wokulski kocha własny idealny obraz Izabeli, nie realną osobę.'],
    ['Racjonalizm','Kartezjusz','Rozum i metodyczne wątpienie są podstawą pewnego poznania.','Starzec w „Romantyczności” uznaje tylko wiedzę sprawdzalną rozumowo.'],
    ['Empiryzm','John Locke, David Hume','Wiedza pochodzi przede wszystkim z doświadczenia i obserwacji; umysł nie rodzi się z gotowymi ideami.','Oświeceniowy kult nauki; Ochocki w „Lalce” poznaje świat przez eksperyment.'],
    ['Utylitaryzm','Jeremy Bentham, John Stuart Mill','Działanie ocenia się przez skutki i pożytek dla możliwie wielu ludzi, ale jednostki nie wolno arbitralnie poświęcić.','Raskolnikow wypacza rachunek korzyści, usprawiedliwiając zabójstwo lichwiarki.'],
    ['Egzystencjalizm','Sartre, Camus','Człowiek nie otrzymuje gotowego sensu; tworzy go przez wolne wybory i ponosi odpowiedzialność w niepewnym świecie.','Rieux w „Dżumie” wybiera solidarne działanie mimo braku gwarancji zwycięstwa.'],
    ['Personalizm','Emmanuel Mounier, Karol Wojtyła','Osoba ma niezbywalną godność, jest celem, a nie narzędziem; spełnia się w odpowiedzialnej relacji z innymi.','Edelman walczy o konkretne życie; totalitaryzmy i teoria Raskolnikowa zaprzeczają personalizmowi.'],
    ['Romantyczny irracjonalizm','romantycy; inspiracje ludowością i mistycyzmem','Rozum nie wyczerpuje poznania; prawdę odsłaniają także uczucie, wiara, intuicja, sen i wizja.','„Romantyczność” przeciwstawia prawdy żywe „szkiełku i oku”.'],
    ['Mesjanizm','Adam Mickiewicz i romantyczna historiozofia','Cierpienie Polski zostaje porównane do męki Chrystusa i ma prowadzić do odrodzenia oraz wolności innych narodów.','Widzenie księdza Piotra w „Dziadach III”.'],
    ['Determinizm','Spinoza; w literaturze także naturalizm','Czyny człowieka są kształtowane przez przyczyny: dziedziczność, środowisko, historię albo prawa natury; wolność może być ograniczona.','Los mieszkańców Lipiec w „Chłopach” wyznaczają natura, wspólnota i ekonomia; bohaterowie „Antygony” mierzą się z fatum.'],
    ['Nihilizm','Nietzsche opisywał kryzys wartości; nie należy utożsamiać go z prostym kultem zła','Brak wiary w trwałe wartości i sens może prowadzić do pustki, relatywizmu albo poszukiwania nowych zasad.','Chaos domu w „Tangu” tworzy próżnię, którą przejmuje Edek; totalitaryzm Orwella niszczy prawdę.']
  ],
  genres: [
    ['Epika','rodzaj literacki: narrator opowiada o świecie przedstawionym','„Lalka”, „Pan Tadeusz”'],['Liryka','rodzaj literacki: centrum stanowią przeżycia i wypowiedź podmiotu lirycznego','pieśni i „Treny”'],['Dramat','rodzaj przeznaczony zasadniczo do wystawienia; dialogi, monologi i didaskalia','„Antygona”, „Wesele”'],['Powieść','obszerny utwór epicki z rozbudowaną fabułą, postaciami i światem','„Lalka”'],['Nowela','krótki, zwarty utwór epicki z jednym głównym wątkiem i wyraźną puentą','„Gloria victis” jako kontekst'],['Epopeja','rozległy utwór o losach wspólnoty na tle przełomowych wydarzeń; styl podniosły','„Pan Tadeusz”, „Iliada”'],['Tragedia','dramat prowadzący do nieuchronnej katastrofy; konflikt tragiczny','„Antygona”, „Makbet”'],['Komedia','dramat wykorzystujący komizm i szczęśliwe rozwiązanie do krytyki wad','„Skąpiec”'],['Dramat romantyczny','forma otwarta, zerwanie z trzema jednościami, synkretyzm, sceny realistyczne i fantastyczne','„Dziady III”'],['Ballada','synkretyczny gatunek łączący epikę, lirykę i dramat, często ludowość i fantastykę','„Romantyczność”'],['Tren','utwór żałobny poświęcony zmarłemu, wyrażający ból i pochwałę','„Treny” Kochanowskiego'],['Hymn','uroczysta pieśń pochwalna do bóstwa, idei lub wspólnoty','„Hymn do miłości ojczyzny”'],['Psalm','biblijna pieśń modlitewna: pochwalna, błagalna, dziękczynna lub pokutna','Psalm 13 i 47'],['Satyra','utwór ośmieszający typowe wady i zjawiska w celu dydaktycznym','„Pijaństwo” Krasickiego'],['Reportaż','opowieść o faktach oparta na dokumentacji i obserwacji autora','„Zdążyć przed Panem Bogiem”'],['Parabola','historia o sensie dosłownym i uniwersalnym, której elementy budują model ludzkiej sytuacji','„Dżuma”'],['Antyutopia','ostrzeżenie przed negatywnym modelem przyszłego społeczeństwa i państwa','„Rok 1984”'],['Groteska','kategoria estetyczna łącząca sprzeczności: komizm z grozą, realizm z absurdem, deformację','„Tango”, „Ferdydurke”']
  ]
};
