const cfg=window.VADEMECUM_CONFIG||{},client=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const routes={polski:'polski.html',angielski:'angielski.html',matematyka:'matematyka.html'};
let user=null,access=[],registerMode=false,pendingSubject=null,purchasedLicense='',checkoutBusy=false;
const $=s=>document.querySelector(s);
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2500)}
function setMessage(message){const box=$('#hubMessage');box.textContent=message;box.hidden=!message}
async function refreshAccess(){access=[];if(user){const {data,error}=await client.rpc('get_my_subject_access');if(error)setMessage('Nie udało się pobrać dostępów. Sprawdź, czy plik SQL został uruchomiony w Supabase.');else access=(data||[]).map(x=>x.subject)}renderHub()}
function renderHub(){$('#userLabel').textContent=user?user.email:'Nie jesteś zalogowany';$('#accountBtn').textContent=user?'Wyloguj się':'Zaloguj się';for(const subject of ['polski','angielski','matematyka']){const unlocked=access.includes(subject),status=$(`[data-status="${subject}"]`),card=$(`[data-subject-card="${subject}"]`),button=$(`[data-open-subject="${subject}"]`);card.classList.toggle('locked',!unlocked);status.textContent=unlocked?'Masz dostęp':'Wymaga klucza';status.className='status'+(unlocked?' unlocked':'');button.textContent=unlocked?`Otwórz ${subject}`:'Aktywuj klucz'}}
function openAuth(){registerMode=false;$('#authTitle').textContent='Zaloguj się';$('#authSubmit').textContent='Zaloguj się';$('#authSwitch').textContent='Nie masz konta? Zarejestruj się';$('#authError').textContent='';$('#authDialog').showModal()}
async function submitAuth(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,errorBox=$('#authError');errorBox.textContent='';if(!email||password.length<6){errorBox.textContent='Podaj e-mail i hasło mające minimum 6 znaków.';return}const button=$('#authSubmit');button.disabled=true;button.textContent='Chwileczkę…';const result=registerMode?await client.auth.signUp({email,password}):await client.auth.signInWithPassword({email,password});button.disabled=false;button.textContent=registerMode?'Utwórz konto':'Zaloguj się';if(result.error){errorBox.textContent=result.error.message;return}if(result.data.session){user=result.data.user;$('#authDialog').close();await refreshAccess();toast('Zalogowano')}else errorBox.textContent='Sprawdź pocztę i potwierdź utworzenie konta.'}
function chooseSubject(subject){pendingSubject=subject;if(!user){openAuth();setMessage('Najpierw zaloguj się, aby otworzyć lub aktywować przedmiot.');return}if(access.includes(subject)){location.href=routes[subject];return}$('#keyTitle').textContent=`Aktywuj: ${subject}`;$('#accessKey').value='';$('#keyError').textContent='';$('#keyDialog').showModal()}
async function redeemKey(){const key=$('#accessKey').value.trim().toUpperCase(),errorBox=$('#keyError');errorBox.textContent='';if(!key){errorBox.textContent='Wpisz klucz dostępu.';return}const button=$('#keySubmit');button.disabled=true;button.textContent='Sprawdzanie…';const {data,error}=await client.rpc('redeem_subject_key',{p_subject:pendingSubject,p_key:key});button.disabled=false;button.textContent='Aktywuj dostęp';if(error){errorBox.textContent='Nie udało się sprawdzić klucza. Spróbuj ponownie.';return}if(!data){errorBox.textContent='Klucz jest nieprawidłowy, został już wykorzystany albo dotyczy innego przedmiotu.';return}$('#keyDialog').close();await refreshAccess();toast('Dostęp został przypisany do Twojego konta');if(routes[pendingSubject])setTimeout(()=>location.href=routes[pendingSubject],450)}

async function buyPremium(){
  const button=$('#buyPremiumBtn'),dialog=$('#checkoutDialog'),status=$('#checkoutStatus'),mount=$('#checkout-form');
  if(checkoutBusy)return;
  if(!cfg.paymentsApiBase){setMessage('Płatności nie są skonfigurowane.');return}
  if(!cfg.stripePublishableKey){setMessage('Brakuje publicznego klucza Stripe (pk_live_...) w config.js.');return}
  if(!window.Stripe){setMessage('Nie udało się załadować Stripe.js.');return}
  checkoutBusy=true;button.disabled=true;button.textContent='Otwieram…';mount.innerHTML='';status.hidden=false;status.textContent='Ładuję bezpieczny formularz Stripe…';dialog.showModal();
  try{
    const res=await fetch(`${cfg.paymentsApiBase}/api/create-checkout`,{method:'POST',headers:{'content-type':'application/json'}}),data=await res.json();
    if(!res.ok||!data.client_secret||!data.session_id)throw new Error(data.error||'Nie udało się rozpocząć płatności.');
    const stripe=Stripe(cfg.stripePublishableKey,{betas:['custom_checkout_payment_form_1']});
    const appearance={theme:'stripe',labels:'auto',inputs:'spaced',variables:{borderRadius:'12px',colorBackground:'#ffffff',colorDanger:'#df1b41',colorPrimary:'#d93b81',colorSuccess:'#198754',colorText:'#30313d',fontFamily:'Nunito, sans-serif',fontSizeBase:'16px',spacingUnit:'4px'}};
    const checkout=stripe.initCheckoutFormSdk({clientSecret:Promise.resolve(data.client_secret),appearance});
    const form=checkout.createForm({layout:'expanded'});form.mount('#checkout-form');
    const actionsResult=await checkout.loadActions();if(actionsResult.type!=='success')throw new Error('Nie udało się przygotować formularza płatności.');
    status.hidden=true;
    form.on('confirm',async event=>{try{status.hidden=false;status.textContent='Finalizuję płatność…';await actionsResult.actions.confirm({formConfirmEvent:event});status.textContent='Płatność przyjęta. Tworzę klucz Premium…';await loadPurchasedKey(data.session_id);dialog.close();}catch(error){status.hidden=false;status.textContent=error?.message||'Nie udało się sfinalizować płatności.';}});
  }catch(error){status.hidden=false;status.textContent=error.message||'Nie udało się rozpocząć płatności.';}
  finally{checkoutBusy=false;button.disabled=false;button.textContent='Kup dostęp za 34,99 zł'}
}
async function loadPurchasedKey(sessionId){if(!cfg.paymentsApiBase)return;$('#purchaseDialog').showModal();$('#purchaseError').textContent='Pobieram klucz…';try{let response,data;for(let i=0;i<5;i++){response=await fetch(`${cfg.paymentsApiBase}/api/checkout-key?session_id=${encodeURIComponent(sessionId)}`);data=await response.json();if(response.ok&&data.license)break;if(response.status!==409)break;await new Promise(r=>setTimeout(r,1200));}if(!response?.ok||!data?.license)throw new Error(data?.error||'Nie udało się pobrać klucza.');purchasedLicense=data.license;$('#purchasedLicense').textContent=data.license;$('#purchaseError').textContent=''}catch(error){$('#purchaseError').textContent=error.message||'Nie udało się pobrać klucza.'}}
document.addEventListener('click',event=>{const open=event.target.closest('[data-open-subject]');if(open)chooseSubject(open.dataset.openSubject)});
$('#accountBtn').onclick=async()=>{if(user){await client.auth.signOut();user=null;access=[];renderHub();toast('Wylogowano')}else openAuth()};
$('#authSubmit').onclick=submitAuth;$('#authSwitch').onclick=()=>{registerMode=!registerMode;$('#authTitle').textContent=registerMode?'Utwórz konto':'Zaloguj się';$('#authSubmit').textContent=registerMode?'Utwórz konto':'Zaloguj się';$('#authSwitch').textContent=registerMode?'Masz już konto? Zaloguj się':'Nie masz konta? Zarejestruj się';$('#authError').textContent=''};
$('#keySubmit').onclick=redeemKey;$('#buyPremiumBtn').onclick=buyPremium;$('#checkoutCloseBtn').onclick=()=>$('#checkoutDialog').close();
$('#copyLicenseBtn').onclick=async()=>{if(!purchasedLicense)return;await navigator.clipboard.writeText(purchasedLicense);toast('Klucz skopiowany')};
$('#activatePurchasedBtn').onclick=()=>{if(!purchasedLicense)return;$('#purchaseDialog').close();pendingSubject='polski';if(!user){openAuth();setMessage('Zaloguj się, a potem aktywuj kupiony klucz.');return}$('#accessKey').value=purchasedLicense;$('#keyTitle').textContent='Aktywuj Premium';$('#keyError').textContent='';$('#keyDialog').showModal()};
(async()=>{if(!client){setMessage('Brak konfiguracji Supabase.');return}const {data}=await client.auth.getSession();user=data.session?.user||null;const params=new URLSearchParams(location.search);if(params.get('locked'))setMessage('Ten przedmiot wymaga zalogowania i aktywnego dostępu.');await refreshAccess();client.auth.onAuthStateChange(async(_,session)=>{user=session?.user||null;await refreshAccess()})})();
