const cfg=window.VADEMECUM_CONFIG||{},client=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const routes={polski:'polski.html',angielski:'angielski.html',matematyka:'matematyka.html'};
let user=null,access=[],registerMode=false,pendingSubject=null,purchasedLicense='';
const $=s=>document.querySelector(s);
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2500)}
function setMessage(message){const box=$('#hubMessage');box.textContent=message;box.hidden=!message}
async function refreshAccess(){access=[];if(user){const {data,error}=await client.rpc('get_my_subject_access');if(error)setMessage('Nie udało się pobrać dostępów. Sprawdź, czy plik SQL został uruchomiony w Supabase.');else access=(data||[]).map(x=>x.subject)}renderHub()}
function renderHub(){$('#userLabel').textContent=user?user.email:'Nie jesteś zalogowany';$('#accountBtn').textContent=user?'Wyloguj się':'Zaloguj się';for(const subject of ['polski','angielski','matematyka']){const unlocked=access.includes(subject),status=$(`[data-status="${subject}"]`),card=$(`[data-subject-card="${subject}"]`),button=$(`[data-open-subject="${subject}"]`);card.classList.toggle('locked',!unlocked);status.textContent=unlocked?'Masz dostęp':'Wymaga klucza';status.className='status'+(unlocked?' unlocked':'');button.textContent=unlocked?`Otwórz ${subject}`:'Aktywuj klucz'}}
function openAuth(){registerMode=false;$('#authTitle').textContent='Zaloguj się';$('#authSubmit').textContent='Zaloguj się';$('#authSwitch').textContent='Nie masz konta? Zarejestruj się';$('#authError').textContent='';$('#authDialog').showModal()}
async function submitAuth(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,errorBox=$('#authError');errorBox.textContent='';if(!email||password.length<6){errorBox.textContent='Podaj e-mail i hasło mające minimum 6 znaków.';return}const button=$('#authSubmit');button.disabled=true;button.textContent='Chwileczkę…';const result=registerMode?await client.auth.signUp({email,password}):await client.auth.signInWithPassword({email,password});button.disabled=false;button.textContent=registerMode?'Utwórz konto':'Zaloguj się';if(result.error){errorBox.textContent=result.error.message;return}if(result.data.session){user=result.data.user;$('#authDialog').close();await refreshAccess();toast('Zalogowano')}else errorBox.textContent='Sprawdź pocztę i potwierdź utworzenie konta.'}
function chooseSubject(subject){pendingSubject=subject;if(!user){openAuth();setMessage('Najpierw zaloguj się, aby otworzyć lub aktywować przedmiot.');return}if(access.includes(subject)){location.href=routes[subject];return}$('#keyTitle').textContent=`Aktywuj: ${subject}`;$('#accessKey').value='';$('#keyError').textContent='';$('#keyDialog').showModal()}
async function redeemKey(){const key=$('#accessKey').value.trim().toUpperCase(),errorBox=$('#keyError');errorBox.textContent='';if(!key){errorBox.textContent='Wpisz klucz dostępu.';return}const button=$('#keySubmit');button.disabled=true;button.textContent='Sprawdzanie…';const {data,error}=await client.rpc('redeem_subject_key',{p_subject:pendingSubject,p_key:key});button.disabled=false;button.textContent='Aktywuj dostęp';if(error){errorBox.textContent='Nie udało się sprawdzić klucza. Spróbuj ponownie.';return}if(!data){errorBox.textContent='Klucz jest nieprawidłowy, został już wykorzystany albo dotyczy innego przedmiotu.';return}$('#keyDialog').close();await refreshAccess();toast('Dostęp został przypisany do Twojego konta');if(routes[pendingSubject])setTimeout(()=>location.href=routes[pendingSubject],450)}
async function buyPremium(){const button=$('#buyPremiumBtn');if(!cfg.paymentsApiBase){setMessage('Płatności nie są jeszcze skonfigurowane. Ustaw adres Workera w config.js.');return}button.disabled=true;button.textContent='Przekierowuję…';try{const res=await fetch(`${cfg.paymentsApiBase}/api/create-checkout`,{method:'POST',headers:{'content-type':'application/json'}});const data=await res.json();if(!res.ok||!data.url)throw new Error(data.error||'Nie udało się rozpocząć płatności.');location.href=data.url}catch(error){setMessage(error.message||'Nie udało się rozpocząć płatności.');button.disabled=false;button.textContent='Kup dostęp'}}
async function loadPurchasedKey(sessionId){if(!cfg.paymentsApiBase)return;$('#purchaseDialog').showModal();$('#purchaseError').textContent='Pobieram klucz…';try{const res=await fetch(`${cfg.paymentsApiBase}/api/checkout-key?session_id=${encodeURIComponent(sessionId)}`);const data=await res.json();if(!res.ok||!data.license)throw new Error(data.error||'Nie udało się pobrać klucza.');purchasedLicense=data.license;$('#purchasedLicense').textContent=data.license;$('#purchaseError').textContent='';history.replaceState({},'',location.pathname)}catch(error){$('#purchaseError').textContent=error.message||'Nie udało się pobrać klucza.'}}
document.addEventListener('click',async event=>{const open=event.target.closest('[data-open-subject]');if(open)chooseSubject(open.dataset.openSubject)});
$('#accountBtn').onclick=async()=>{if(user){await client.auth.signOut();user=null;access=[];renderHub();toast('Wylogowano')}else openAuth()};
$('#authSubmit').onclick=submitAuth;
$('#authSwitch').onclick=()=>{registerMode=!registerMode;$('#authTitle').textContent=registerMode?'Utwórz konto':'Zaloguj się';$('#authSubmit').textContent=registerMode?'Utwórz konto':'Zaloguj się';$('#authSwitch').textContent=registerMode?'Masz już konto? Zaloguj się':'Nie masz konta? Zarejestruj się';$('#authError').textContent=''};
$('#keySubmit').onclick=redeemKey;
$('#buyPremiumBtn').onclick=buyPremium;
$('#copyLicenseBtn').onclick=async()=>{if(!purchasedLicense)return;await navigator.clipboard.writeText(purchasedLicense);toast('Klucz skopiowany')};
$('#activatePurchasedBtn').onclick=()=>{if(!purchasedLicense)return;$('#purchaseDialog').close();pendingSubject='polski';if(!user){openAuth();setMessage('Zaloguj się, a potem aktywuj kupiony klucz.');return}$('#accessKey').value=purchasedLicense;$('#keyTitle').textContent='Aktywuj Premium';$('#keyError').textContent='';$('#keyDialog').showModal()};
(async()=>{if(!client){setMessage('Brak konfiguracji Supabase.');return}const {data}=await client.auth.getSession();user=data.session?.user||null;const params=new URLSearchParams(location.search);if(params.get('locked'))setMessage('Ten przedmiot wymaga zalogowania i aktywnego dostępu.');if(params.get('checkout')==='cancelled')setMessage('Płatność została anulowana.');await refreshAccess();const sessionId=params.get('session_id');if(params.get('checkout')==='success'&&sessionId)await loadPurchasedKey(sessionId);client.auth.onAuthStateChange(async(_,session)=>{user=session?.user||null;await refreshAccess()})})();
