-- Premium access key system for Matura 2027
-- Run this once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.access_keys (
  id bigint generated by default as identity primary key,
  key_hash text not null unique,
  subject text not null check (subject in ('polski','angielski','matematyka','premium')),
  active boolean not null default true,
  redeemed_by uuid references auth.users(id) on delete set null,
  redeemed_at timestamptz,
  stripe_session_id text unique,
  purchaser_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.subject_access (
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (subject in ('polski','angielski','matematyka')),
  source text not null default 'key',
  created_at timestamptz not null default now(),
  primary key (user_id, subject)
);

alter table public.access_keys enable row level security;
alter table public.subject_access enable row level security;

-- Users can only read their own granted subjects. They cannot browse access keys.
drop policy if exists "users read own subject access" on public.subject_access;
create policy "users read own subject access"
on public.subject_access for select
using (auth.uid() = user_id);

create or replace function public.get_my_subject_access()
returns table(subject text)
language sql
security definer
set search_path = public
as $$
  select sa.subject
  from public.subject_access sa
  where sa.user_id = auth.uid();
$$;

revoke all on function public.get_my_subject_access() from public;
grant execute on function public.get_my_subject_access() to authenticated;

create or replace function public.redeem_subject_key(p_subject text, p_key text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_key public.access_keys%rowtype;
  v_hash text;
begin
  if v_user is null then
    return false;
  end if;

  if p_subject not in ('polski','angielski','matematyka') then
    return false;
  end if;

  v_hash := encode(digest(upper(trim(p_key)), 'sha256'), 'hex');

  select * into v_key
  from public.access_keys
  where key_hash = v_hash
    and active = true
    and redeemed_by is null
    and (subject = p_subject or subject = 'premium')
  for update skip locked;

  if not found then
    return false;
  end if;

  update public.access_keys
  set redeemed_by = v_user,
      redeemed_at = now(),
      active = false
  where id = v_key.id;

  if v_key.subject = 'premium' then
    insert into public.subject_access(user_id, subject, source)
    values
      (v_user, 'polski', 'premium-key'),
      (v_user, 'angielski', 'premium-key'),
      (v_user, 'matematyka', 'premium-key')
    on conflict (user_id, subject) do nothing;
  else
    insert into public.subject_access(user_id, subject, source)
    values (v_user, p_subject, 'subject-key')
    on conflict (user_id, subject) do nothing;
  end if;

  return true;
end;
$$;

revoke all on function public.redeem_subject_key(text,text) from public;
grant execute on function public.redeem_subject_key(text,text) to authenticated;
