-- Premium access key system for Matura 2026
-- Compatible with legacy subject_access_keys + subject_entitlements.
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.access_keys (
  id bigint generated by default as identity primary key,
  key_hash text not null unique,
  subject text not null check (subject in ('polski','angielski','matematyka','premium')),
  active boolean not null default true,
  redeemed_by uuid references auth.users(id) on delete set null,
  redeemed_at timestamptz,
  stripe_session_id text unique,
  purchaser_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.subject_access (
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (subject in ('polski','angielski','matematyka')),
  source text not null default 'key',
  created_at timestamptz not null default now(),
  primary key (user_id, subject)
);

alter table public.access_keys enable row level security;
alter table public.subject_access enable row level security;

drop policy if exists "users read own subject access" on public.subject_access;
create policy "users read own subject access"
on public.subject_access for select
using (auth.uid() = user_id);

insert into public.subject_access(user_id, subject, source, created_at)
select user_id, subject, 'legacy-entitlement', granted_at
from public.subject_entitlements
on conflict (user_id, subject) do nothing;

create or replace function public.get_my_subject_access()
returns table(subject text)
language sql
security definer
set search_path = public, extensions
as $$
  select sa.subject
  from public.subject_access sa
  where sa.user_id = auth.uid()
  union
  select se.subject
  from public.subject_entitlements se
  where se.user_id = auth.uid();
$$;

revoke all on function public.get_my_subject_access() from public;
grant execute on function public.get_my_subject_access() to authenticated;

-- Main redemption RPC used by the website.
-- The browser computes SHA-256, so this RPC does not depend on pgcrypto/digest at runtime.
create or replace function public.redeem_subject_key_hash(p_subject text, p_key_hash text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_new_id bigint;
  v_new_subject text;
  v_legacy_id uuid;
begin
  if v_user is null then return false; end if;
  if p_subject not in ('polski','angielski','matematyka') then return false; end if;
  if p_key_hash is null or length(p_key_hash) <> 64 then return false; end if;

  select ak.id, ak.subject
    into v_new_id, v_new_subject
  from public.access_keys ak
  where ak.key_hash = lower(trim(p_key_hash))
    and ak.active = true
    and ak.redeemed_by is null
    and (ak.subject = p_subject or ak.subject = 'premium')
  for update skip locked
  limit 1;

  if v_new_id is not null then
    update public.access_keys
    set redeemed_by = v_user,
        redeemed_at = now(),
        active = false
    where id = v_new_id;

    if v_new_subject = 'premium' then
      insert into public.subject_access(user_id, subject, source)
      values
        (v_user, 'polski', 'premium-key'),
        (v_user, 'angielski', 'premium-key'),
        (v_user, 'matematyka', 'premium-key')
      on conflict (user_id, subject) do nothing;
    else
      insert into public.subject_access(user_id, subject, source)
      values (v_user, p_subject, 'subject-key')
      on conflict (user_id, subject) do nothing;
    end if;

    return true;
  end if;

  select sak.id
    into v_legacy_id
  from public.subject_access_keys sak
  where sak.key_hash = lower(trim(p_key_hash))
    and sak.redeemed_by is null
    and sak.subject = p_subject
  for update skip locked
  limit 1;

  if v_legacy_id is null then return false; end if;

  update public.subject_access_keys
  set redeemed_by = v_user,
      redeemed_at = now()
  where id = v_legacy_id;

  insert into public.subject_entitlements(user_id, subject, granted_at, access_key_id)
  values (v_user, p_subject, now(), v_legacy_id)
  on conflict do nothing;

  insert into public.subject_access(user_id, subject, source)
  values (v_user, p_subject, 'legacy-key')
  on conflict (user_id, subject) do nothing;

  return true;
end;
$$;

revoke all on function public.redeem_subject_key_hash(text,text) from public;
grant execute on function public.redeem_subject_key_hash(text,text) to authenticated;

-- Backward-compatible plain-text RPC for older frontend versions.
create or replace function public.redeem_subject_key(p_subject text, p_key text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_hash text;
begin
  v_hash := encode(digest(upper(trim(p_key)), 'sha256'), 'hex');
  return public.redeem_subject_key_hash(p_subject, v_hash);
end;
$$;

revoke all on function public.redeem_subject_key(text,text) from public;
grant execute on function public.redeem_subject_key(text,text) to authenticated;
